### ISSUE TITLE
Improving clarity in logfile-definitions examples

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1020]
This is a small one, likely for @jeffriley 

It's a bit non-intuitive to find the names of the logfiles as they should be specified in the `--logfile-definitions` input. Most of them can be found in the documentation [here.](https://compas.readthedocs.io/en/latest/pages/User%20guide/COMPAS%20output/standard-logfiles-example-definitions-file.html). However, some of them seem to use a funny shorthand (e.g `sysparms` comes up a lot, when `sysparams` would make more sense). Also, not all of them are present. I needed to amend the BSE_SWITCH_LOG output, and the keyname for this one isn't present in the documentation, so I had to dig through the source code to find that it is `bse_switch_rec`. 

I think the functionality here is great, but the documentation around it is a bit cryptic. At the very least, it would be valuable to see in this page of the documentation, a 1:1 list of the name keywords and their respective `BSE_..._REC` output files. 

Edit: I can also take care of this if we decide it's just a documentation change, but for anything more substantial it will require greater expertise.

**Comment by jeffriley** [comment]
> I needed to amend the BSE_SWITCH_LOG output, and the keyname for this one isn't present in the documentation

It is - here:

https://compas.readthedocs.io/en/latest/pages/User%20guide/COMPAS%20output/standard-logfiles-record-specification.html


> sysparms comes up a lot, when sysparams would make more sense

"parms" has been the abbreviation for "parameters" for as long as I can remember, but if enough people want to change it I don't really have an objection - other than changing things that may have made their way into people's configuration files means they will have to go and change all their files...

I did make the names shorthand - simply so people wouldn't have to type long names all the time - but I'm not wedded to them.  And since you found the table in the code when you located `BSE_SWITCH_REC` you can see that it's not hard to change.

**Comment by jeffriley** [comment]
@reinhold-willcox It has been a few days and nobody else has commented - I'll leave it a few more days for people to
comment if they want to, but as it stands I don't think we should change the name of any of the record names for the logfile-definitions file.  They are all documented, as noted in the previous post.

Wrt "sysparms" - as I said in the previous post, "parms" has been an accepted abbreviation for "parameters" since I first started programming in the mid-1970s - see e.g.

    https://www.pcmag.com/encyclopedia/term/parm
    https://www.computerlanguage.com/results.php?definition=PARM
    https://www.computerhope.com/jargon/p/paramete.htm
    https://www.allacronyms.com/PARM
    https://www.acronymfinder.com/Parameter-(PARM).html

Also, from one of the biggest computer manufacturers:

    https://www.ibm.com/docs/en/i/7.2?topic=keywords-cl-command-keyword-abbreviations
    https://www.ibm.com/docs/en/i/7.2?topic=plist-using-parm-operation

and one of the biggest software houses:

https://documentation.sas.com/doc/da/pgmsascdc/v_015/etsug/etsug_model_sect049.htm#:~:text=The%20PARAMETERS%20statement%20declares%20the,the%20same%20for%20all%20observations

Moreover, if we change the name then any users that have stored project-specific logfile-definitions files that use the existing names will have to change their files.  I just don't think it is necessary, but if enough people comment here they'd like to see the names changed, then by all means, change them (you just need to change the `LOGFILE_DESCRIPTOR` table in `constants.h`.

As far as adding a table to the documentation that maps logfiles to the logfile-definitions record names, something like:

    SSE System Parameters file           uses the record name "SSE_SYSPARMS_REC"
    SSE Supernovae file                      uses the record name "SSE_SNE_REC"
    SSE Detailed Output file               uses the record name "SSE_DETAILED_REC"
    SSE Switch Log file                        uses the record name "SSE_SWITCH_REC"
    
    BSE System Parameters file           uses the record name "BSE_SYSPARMS_REC"
    BSE Supernovae file                      uses the record name "BSE_SNE_REC"
    BSE Double Compact Objects file uses the record name "BSE_DCO_REC"
    BSE Common Envelopes file         uses the record name "BSE_CEE_REC"
    BSE Pulsar Evolution file               uses the record name "BSE_PULSARS_REC"
    BSE RLOF Parameters file              uses the record name "BSE_RLOF_REC"
    BSE Detailed Output file               uses the record name "BSE_DETAILED_REC"
    BSE Switch Log file                       uses the record name "BSE_SWITCH_REC"

You could do that if you think it is necessary, but I don't think the record names are so abstruse that users can't link them to the correct file.

**Comment by ilyamandel** [comment]
@reinhold-willcox , @jeffriley : all log files (including bse_switch_rec) appear in https://compas.readthedocs.io/en/latest/pages/User%20guide/COMPAS%20output/standard-logfiles-record-specification.html -- so I think we are OK on documentation.  

I 100% agree with Jeff that we should not be changing "external-facing" names unless absolutely critical.

**Comment by jeffriley** [comment]
No follow-up - closing.
