### ISSUE TITLE
Disrupted systems incorrectly remaining bound

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1031]
**Describe the bug**
The following system disrupts during the first supernova, and correctly shows a negative semi-major axis in the `BSE_Supernovae` output. However, the system continues evolving and at the end of the evolution, shows a positive semi-major axis again (as indicated in the `BSE_System_Parameters` output), suggesting that the disruption is not correctly treated. Notably, this system ends with "Stars touching" when the secondary expands off the MS, even when the timestep resolution is reduced to 0.1.

**Label the issue**
`urgency_high`     - This is a very urgent issue and should be resolved as soon as possible
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
```
 --random-seed 1702303386 --initial-mass-1 14.309862031562341 --initial-mass-2 6.708617619250256 --semi-major-axis 0.1515625145982062
```

**Expected behavior**
The system should end as an unbound binary (since we have not enabled the flag to evolve unbound binaries). 

**Versioning (please complete the following information):**
 - COMPAS v02.41.02

**Comment by jeffriley** [comment]
Looking at the detailed output we see where the semi-major axis goes negative, then goes positive again:

    RECORD_TYPE SYMBOLIC NAME        SEMI-MAJOR AXIS  
        14      POST-MASS-RESOLUTION 32.59221
        13      POST-SN              -24.78353
         3      POST-BINARY-TIMESTEP -24.78353
         4      TIMESTEP-COMPLETED   -24.78353
         2      POST_STELLAR-TIMESTEP -24.78353
        10      POST-MT              -24.78353
        11      POST-WINDS           -24.78353
        14      POST-MASS-RESOLUTION 32.59129

(Record types are in `BSE_DETAILED_RECORD_TYPE` in `constants.h`)

So I believe what is happening is that the binary is unbound as a result of the SN event, but in the post-mass-resolution code the semi-major axis being recalculated as positive.  That's happening in `BaseBinaryStar::ResolveMassChanges()` at the following statement:

    m_SemiMajorAxis = m_SemiMajorAxisPrev + m_aMassLossDiff + m_aMassTransferDiff;

(BaseBinaryStar.cpp line 2220 in v02.41.02)

`--evolve-unbound-systems` is `TRUE` by default, so we are evolving unbound systems.  When we enter `BaseBinaryStar::EvaluateBinary()` on the next timestep, the binary is still unbound, and since it's not a CEE or merger, and no longer a SN event (that was the last timestep), we proceed to resolve mass changes, and calculate a positive semi-major axis.  What should happen here?

**Comment by ilyamandel** [comment]
Once the binary is unbound, we should not be updating the orbital
parameters at all in response to things like wind mass loss, since they are
meaningless from that point onwards (the negative semimajor axis is just a
reminder that the binary is unbound, not a physical value).

Just to confirm, this is really a response to mass loss post SN, not a
Blaauw kick from the SN itself, right?

**Comment by jeffriley** [comment]
> Just to confirm, this is really a response to mass loss post SN

I believe so.  We're calling BaseBinaryStar::ResolveMassChanges() as part of the ordinary evolution of a binary.  In the statement

    m_SemiMajorAxis = m_SemiMajorAxisPrev + m_aMassLossDiff + m_aMassTransferDiff;

`m_aMassLossDiff` is close to zero (~1x10^-9), and `m_aMassTransferDiff` is 0 - the problem is that we're setting `m_SemiMajorAxis` at all, and using `m_SemiMajorAxisPrev`.  So we should just skip the entire function?  But what does it actually mean to evolve the unbound system?  Are we just evolving two individual stars now, so should just do SSE at each timestep and skip over the BSE code?  That's not what we do.

**Comment by ilyamandel** [comment]
Thank you for confirming!

Yes, we should basically evolve the two stars independently, just keeping
track of their individual velocities in the frame of the original binary's
center of mass.

**Comment by reinhold-willcox** [comment]
For some reason, this issue seems to have solved itself. I can no longer reproduce the buggy behavior for the system given above, but instead the binary disrupts as we would expect. Perhaps this was an issue related to the strange git merge that occurred late last year. 

Unless anyone would like to dig into this further, I'm happy to close this issue.
