### ISSUE TITLE
HeGiant stability condition doesn't make sense

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1056]
**Describe the bug**
In `BaseBinaryStar.cpp`, when we go to calculate MT stability, we have the following clause:

```
     // Determine stability
     bool isUnstable;
     if (donorIsHeHGorHeGB && (caseBBAlwaysStable || caseBBAlwaysUnstable || (caseBBAlwaysUnstableOntoNSBH && accretorIsNSorBH))) { // Determine stability based on case BB 
         isUnstable = (caseBBAlwaysUnstable || (caseBBAlwaysUnstableOntoNSBH && accretorIsNSorBH));                              // Already established that donor is HeHG or HeGB - need to check if new case BB prescriptions are added
     }
```

The `caseBBAlwaysStable` condition is incorrectly absent from the logic in setting `isUnstable`. Likely this is a simple fix, but it would be good to thoroughly check this for all the different logic paths. We may also want to rewrite it to be clearer. I haven't checked how impactful this is to the evolution, but it likely affects DNS formation.

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**Versioning (please complete the following information):**
 - COMPAS v02.41.04

**Comment by ilyamandel** [comment]
@reinhold-willcox -- I don't see the problem here.  If `caseBBAlwaysStable`, we won't need to set `isUnstable`, which remains false by default.

**Comment by jeffriley** [comment]
We could change:

    bool isUnstable;

to

    bool isUnstable = false;

just to make that explicit (but, as @ilyamandel says, it will default to false).

**Comment by jeffriley** [comment]
`caseBBAlwaysStable` is ORed into part of the conditional - that's probably superfluous (though I haven't put a lot of thought into that...)

**Comment by ilyamandel** [comment]
@jeffriley -- I agree.  I'll change the issue tags, but keep it open to remind us to make these cosmetic tweaks.

**Comment by reinhold-willcox** [comment]
Yes of course, caseBBAlwaysStable, caseBBAlwaysUnstable, and caseBBAlwaysUnstableOntoNSBH are not independently set, so the condition is fine as is. 

I'm happy to close the issue, but a quick question first: how do you know that a declared (but not defined) boolean will default to False? There seems to be some discussion about it online that it may be context dependent?

**Comment by jeffriley** [comment]
@reinhold-willcox is absolutely right - I had forgotten this - good catch @reinhold-willcox.

The standard requires that c++ compilers initialise global variables and local variables with static storage duration.  Technically all local variables in c++ are scoped lexically, which could be interpreted to mean they have static storage duration, so I think that's the source of the debate.  Declaring a local variable as static is different - a local variable that is declared static will be initialised when it is declared, and its value will be retained across calls to the function.  Local variables that are not declared static are stored in the stack frame of the function in which they are declared, and because the standard doesn't require that c++ compilers initialise non-static local variables, the compiler may just assign the local variable a memory address (relative to the stack marker) and use that piece of memory without first writing the type constructor initialiser to it, so the variable's initial value will be whatever happens to be in that memory location (if the stack had been dynamically growing and shrinking as functions are called, then it might have been used and have some (to us) spurious value in it.

So, yes, local variables may not be initialised (it may be - it depends upon what the specific compiler being used does - the standard doesn't require initialisation of local variables, but that doesn't mean it prohibits it) - another reason it is always good practice to explicitly initialise variables.

We did say above we'd do that, so we should have this case covered - but we should keep this in mind as we create new code or read existing code and just make sure we explicitly initialise variables.

**Comment by reinhold-willcox** [comment]
Thanks for the in depth explanation!
