### ISSUE TITLE
Documentation on EVOLUTION_STATUS is out of date

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1098]
**Describe the bug**
The documentation on EVOLUTION_STATUS is found here:
https://compas.readthedocs.io/en/latest/pages/User%20guide/COMPAS%20output/standard-logfiles-record-specification-binary.html

There are only 14 entries, which is inconsistent with what is currently in the source code, which has 18. The documentation needs to be updated. This is an easy fix, and probably good for a first issue for any new devs. 

`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

 - COMPAS v02.43.00

**Comment by jeffriley** [comment]
Thanks @reinhold-willcox . Someone else pointed this out recently (might have been @veome22, or maybe I just noticed it...), and I meant to fix it in the next PR I did, but I forgot...  You're right, the fix is trivial, so if someone else gets to it before my next PR, great, otherwise I'll do it in my next PR (assuming I remember...).

**Comment by ilyamandel** [comment]
Fixed in #1108
