### ISSUE TITLE
Weird error: cannot create first entry in BSE_System_Parameters output when using Eccentricity in logfile and a grid.

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1160]
**Describe the bug**
This is a weird one, occuring only in a specific corner case. When I use `--logfile-definitions` with a logfile that includes eccentricity in `BSE_SYSPARMS_REC`, and I also include a gridfile, I get an error `ERROR: Unable to create HDF5 dataSet Eccentricity for file BSE_System_Parameters`. However, this error only shows up for the first simulated binary, which means this first system does not show up in the `BSE_System_Parameters` output. 

Weirdly, despite this error, all the other systems which appear in BSE_System_Parameters have eccentricity values (all set to 0, as expected). Even more weirdly, the error goes away if I do not use a gridfile. 

**Label the issue**
`urgency_moderate`      - This issue is not urgent
`severity_moderate`    - This is a minor bug with minimal impact

**To Reproduce**
Here's a MWE:

```
#logfile.txt
 BSE_SYSPARMS_REC += {
     BINARY_PROPERTY::ECCENTRICITY,
 }

#grid.txt
--initial-mass-1 10
--initial-mass-1 9

COMPAS --logfile-def logfile.txt --grid grid.txt 
```

If you run this, you will see the error only before the first output entry, and `BSE_System_Parameters` will contain only the second entry in the grid. 

**Expected behavior**
There should be no error, and the system should be present in the BSE_System_Parameters.

**Versioning (please complete the following information):**
 - COMPAS v02.49.04

**Comment by jeffriley** [comment]
Ah...

This won't happen if you use `--add-options-to-sysparms never` (the default is `grid`).  It turns out that the binary property 'Eccentricity' has the same header string as the program option 'Eccentricity', so when we add the program options to the sysparms file we have two columns with the same header string - and for HDF5 the header string is the dataset name, so we try to create a second dataset named 'Eccentricity' and fail there.

This hasn't been encountered before because the binary property 'Eccentricity' is not part of the system parameters file by default - 'Initial_Eccentricity' is.

The fix is easy - we'll just have to change one of the header strings - I think best if we change the program option header string (maybe they should all be prefixed with "PO_" or something).

I'll push a fix soon, but in the meantime you can workaround the problem by not adding the program options to the system parameters file...

**Comment by reinhold-willcox** [comment]
Thanks Jeff!
