### ISSUE TITLE
program option to create log of WD binaries

### ISSUE THREAD

**Issue by dumbscholar** [TeamCOMPAS/COMPAS#1170]
It would be nice to have a program option to (whether or not to) include WDs in the double compact objects log. Or there can be separate log file altogether with WD-WD, WD-NS and WD-BH binaries. Along with this, individual WDs can be allowed to evolve in their respective binaries.

**Comment by ilyamandel** [comment]
I agree, this could go into the DCO log.  This may actually couple well to some of the work @Adam-Boesky is doing.

**Comment by jeffriley** [comment]
> It would be nice to have a program option to (whether or not to) include WDs in the double compact objects log.

I think this can be achieved easily by changing the definition of `BaseBinaryStar::IsDCO()` to include White Dwarfs if the option is enabled.  I think we'd have to check if `--evolve-double-white-dwarfs` was enabled so that we don't stop when we have a DCO if the user wants to evolve WDWD.  Otherwise I don't think there's anything else to do.

**Comment by jeffriley** [comment]
PR https://github.com/TeamCOMPAS/COMPAS/pull/1208 opened.
