### ISSUE TITLE
Intermediate-mass stars may have unrealistic convective envelope masses and radii

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#1180]
GiantBranch::CalculateConvectiveEnvelopeMass() calculates the mass of the convective envelope using the Picker, Hirai, Mandel (2024) formalism for all GB stars, even though the formalism was calibrated for massive stars only.  We should check whether these fits yield reasonable results for intermediate-mass stars and if not, revert to Hurley+ fits below the mass applicability threshold of Picker+ fits, at least for now.

The radial extent of the convective envelope is calculated in HG.h CalculateRadialExtentConvectiveEnvelope() on the basis of the current and maximum convective envelope core mass.  I suspect a poor fit to the latter is particularly problematic for intermediate mass stars, and is leading to artefacts such as extremely low convective envelope radii / high densities. For now, I will cap the maximum convective envelope mass for intermediate mass stars to the total envelope mass (since such stars have a negligible radiative intershell late in their evolution). 

However, more careful investigation is required, so creating an issue for this.

**Comment by veome22** [comment]
Here are a few tests I ran for for additional context, comparing the convective envelope masses and radii between the Hurley+(2000) and the Picker, Hirai, Mandel (2024) models.

The dashed lines correspond to the onset of HG and FGB. 

Generally speaking, below initial masses of 7 $M_\odot$, the convective envelope grows too abruptly for HG stars in the Picker+ (2024) model. The Hurley model seems to do a better job here. Both models are somewhat consistent with the envelope mass at the base of the FGB, although of course the Picker+(2024) model produces a continuous curve.

At and above initial masses of 7 $M_\odot$, the Picker+ (2024) model predicts no convective envelope mass on the Giant Branch. While the Picker+(2024) model is consistent with this along the HG, the Hurley+ (2000) model results in a significant convective envelope by the end of the HG. 

|  Mass  | Radius |
| ------------- | ------------- |
|   <img width="1084" alt="image" src="https://github.com/user-attachments/assets/b2da5304-ed37-4f3a-9760-177037f8fdf3"> | <img width="959" alt="image" src="https://github.com/user-attachments/assets/f2b8aaa4-2e8f-4f8b-93b6-53419d070fe9"> |
| <img width="1147" alt="image" src="https://github.com/user-attachments/assets/a2cce7c0-97a3-4166-b071-6455ac335b95"> | <img width="1071" alt="image" src="https://github.com/user-attachments/assets/03c52666-c2ee-4dbc-a331-0dd6a9782e09"> |
| <img width="1147" alt="image" src="https://github.com/user-attachments/assets/ddc2be63-8f11-4643-8950-8ac9d0dc64d1"> | <img width="1071" alt="image" src="https://github.com/user-attachments/assets/f518e7a2-549f-421d-bdfa-bc83ebfa7040"> |
|  <img width="1078" alt="image" src="https://github.com/user-attachments/assets/91fdb0c5-78ec-4e00-a2e4-b14db327f1b3"> | <img width="1096" alt="image" src="https://github.com/user-attachments/assets/763ce38b-4876-4be3-a144-d445ac0cfdc3"> |



Based on these tests, my suggestion is to use the Picker+(2024) model for stars with $M_{\rm ZAMS} \geq 7 M_\odot$.

@ilyamandel I don't understand why the GB convective envelope mass in the Picker+ should be so different between stars with initial masses above vs below 7 $M_\odot$. Specifically, why is there a significant convective envelope below 7 $M_\odot$, and nothing above 7 $M_\odot$. Note that the convective envelope in the 7 $M_\odot$ star develops on the 

Also, there is a discontinuity in the convective envelope mass and radius when going from GB to CHeB (not marked here, but that's the cliff-looking structure right after the GB dashed line in the $6.9 M_\odot$ and $7 M_\odot$ plots). Is this by design?

**Comment by ilyamandel** [comment]
Hi @veome22 ,

Sorry, just returning to this now.  I am quite perplexed by these findings -- these are not what I would have expected.  Definitely requires some further investigation.  

The sharp change in the behaviour at ~7 solar masses could be due to my attempt to only apply the Picker prescription for the maximum mass of the convective envelope to massive stars, and not to stars with core masses below 1.5 Msun...

From GiantBranch::CalculateConvectiveEnvelopeMass():
    if( utils::Compare(McoreFinal,1.5) < 0 )                                                                                // Picker+ 2024 fits were only made for stars above 8.0 solar masses, with runs down to 5.0 solar masses, so using the final core mass as an approximate threshold of validity
        MconvMax                  = m_Mass - McoreFinal;                                                                    // unlike massive stars, intermediate-mass stars have almost no radiative intershell at maximum convective envelope extent

**Comment by ilyamandel** [comment]
I looked at the code, and there are some things I definitely want to fix.  These include:
- Check if AGB donors are being treated correctly in the Picker formulae.
- Make sure that Mfinal-Mcore (around line 1075 of GiantBranch.cpp) is always positive [it probably is]
- The convective envelope radius looks like it might jump at the end of the HG; it shouldn't -- the HG prescription should be smoothly continued to FGB/CHeB.

That said, I don't understand a lot of the plots shared above (e.g., why do 15 Msun stars have fully radiative envelopes in both Picker and Hurley models -- I'd expect the opposite?).  To be continued.

**Comment by veome22** [comment]
> That said, I don't understand a lot of the plots shared above (e.g., why do 15 Msun stars have fully radiative envelopes in both Picker and Hurley models -- I'd expect the opposite?). To be continued.

Do you mean after the Hertzsprung Gap? I have been using the same model (Picker+) in both cases for anything after HG, so they should be trivially the same. Apologies, I should have clarified earlier.

Where I mark 'GB' on my plots, I should have actually marked 'CheB'. At this point, the star has a total mass $14.8 M_\odot$ and radius $68.3 R_\odot$. 

At the start of CHeB, though there is a large radial extent for the convective envelope ($67.8 R_\odot$), and the Picker+ model predicts a max. convective envelope mass of($9.7 M_\odot$), the actual mass of the convective envelope is close to zero ($10^{-109}$). 

The radiative shell is the opposite: the mass of the radiative region is $11.1 M_\odot$, because this is inferred from the lack of convective envelope. The radial extent is only $0.5 R_\odot$.

**Comment by ilyamandel** [comment]
I implemented the updates to the Picker convective envelope mass and radial extent fits mentioned above in #1226 .

This should, for example, fix the issue @veome22 mentioned with the convective envelope radial extent evolving discontinuously from the HG to the CHeB phases.

**Comment by ilyamandel** [comment]
Hi @veome22 ,
I think (hope) that all of the issues marked here are resolved in PR #1230 , so I would appreciate you taking a look and running your tests, since they are a bit different from mine.  Happy to explain things in more detail if they aren't clear from the code.

**Comment by ilyamandel** [comment]
Fixed in #1230 , closing.
