### ISSUE TITLE
Should we use a combination of common envelope formalisms?

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#1213]
We currently have two options for --common-envelope-formalism, namely 'TWO_STAGE' from Hirai & Mandel and the classic 'ENERGY' (alpha) formalism.

If I understand correctly, the two-stage common envelope formalism is really meant to be for massive stars, whilst the alpha formalism is better suited to low-mass stars. For studies that focus on one of these mass regimes, the informed user can pick the relevant prescription, or test what impact changing between these has.

However, if one wishes to explore a range of masses that includes low-mass and massive stars, then it might make more sense to have some mass (and/or other criteria) at which we switch between these prescriptions.

Thoughts welcome.

**Comment by ilyamandel** [comment]
Hi @SimonStevenson ,

@ryosuke-hirai and I discussed this today.

There is no smooth way to attach the 2-stage formalism and standard alpha-lambda formalism, because even when the envelope if fully convective, they use different lambda prescriptions (and potentially different alpha values).  Therefore, combining them would inevitably lead to undesirable discontinuous behaviour at the transition point.

That said, there's a good case to be made that in low and intermediate mass stars, the entropy profile in the envelope is much smoother than in massive stars.  In other words, the distinction between the part of the envelope that expands on a dynamical timescale vs. the slower, thermal-timescale portion moves inward from the convective/radiative boundary as mass decreases.  We therefore propose a "smoothed" version of the 2-stage CE, to behave as follows:

If M_total > 8 Msun, the mass of the envelope participating in the first stage, M_1, is the mass of the convective outer envelope M_conv (as in the current 2-stage model)
If M_total < 2 Msun, the entire envelope participates in the first stage, M_1 = M_env.
In between, we smoothly interpolate: M_1 = M_conv + f * M_rad,
where f = 1 - (M_total - 2 Msun)/(6 Msun), and M_rad is the radiative intershell mass, M_rad = M_total - M_conv - M_core.

If there are no objections, I will implement this.

**Comment by ilyamandel** [comment]
In the absence of objections, implemented in #1226 , closing.

Two notes: 
1) I just made this the single default rather than adding another option.
2) I still use the Picker fits as applied to just the convective envelope mass to estimate lambda, in the absence of better options.
