### ISSUE TITLE
Slow performance in v3.09.00+

### ISSUE THREAD

**Issue by dumbscholar** [TeamCOMPAS/COMPAS#1293]
The COMPAS runtime has increased two fold since v3.09.00. With this version, it takes around 5.5 hrs to evolve 1 million 5-150 M_Sun binaries compared to 2.5-3.0 hrs before (example v3.07.02 or v3.08.04).

Run command:

--mode 'BSE' --initial-mass-min 5.0 --eccentricity-distribution 'THERMAL' --number-of-systems 1000000 --switch-log False --detailed-output False --logfile-type 'CSV' --allow-rlof-at-birth False --logfile-supernovae '' --logfile-common-envelopes '' --logfile-rlof-parameters '' --logfile-system-parameters '' --random-seed 0 --metallicity 0.0001 --output-container Z.0001

**Comment by ilyamandel** [comment]
The nuclear timescale mass transfer, which is now finally being done correctly (I hope!), lasts over many more time steps than it used to.  So this really can be the bottleneck.  Especially since we put every line of it into the RLOF file.  We may want to think about how to write out only summary information (unless the user asks for details), if logging is indeed the bottleneck.  But I'd prefer to fix remaining issues and make sure we have all the physics right before worrying about runtime too much.  So suggest not worrying about optimisation yet -- and when we do tackle it, we should couple it with ensuring convergence and optimising timesteps accordingly (see #24 ).
