### ISSUE TITLE
COMPAS installation errors

### ISSUE THREAD

**Issue by zuozyu** [TeamCOMPAS/COMPAS#216]
I’m installing COMPAS following https://github.com/TeamCOMPAS/COMPAS/blob/master/docs/getting_started.md,
However, when  compile  by running make -f Makefile. I have the following errors,

…
constants.h:828:1: error: converting to 'const std::tuple<ERROR_SCOPE, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = ERROR_SCOPE; _U2 = const char (&)[53]; <template-parameter-2-3> = void; _T1 = ERROR_SCOPE; _T2 = std::__cxx11::basic_string<char>]'
constants.h:828:1: error: converting to 'const std::tuple<ERROR_SCOPE, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = ERROR_SCOPE; _U2 = const char (&)[50]; <template-parameter-2-3> = void; _T1 = ERROR_SCOPE; _T2 = std::__cxx11::basic_string<char>]'
constants.h:828:1: error: converting to 'const std::tuple<ERROR_SCOPE, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = ERROR_SCOPE; _U2 = const char (&)[9]; <template-parameter-2-3> = void; _T1 = ERROR_SCOPE; _T2 = std::__cxx11::basic_string<char>]'
constants.h:1533:1: error: converting to 'const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[5]; _U2 = const char (&)[5]; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]'
 };
 ^
constants.h:1533:1: error: converting to 'const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[5]; _U2 = const char (&)[5]; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]'
constants.h:1533:1: error: converting to 'const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[10]; _U2 = const char (&)[4]; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]'
constants.h:1533:1: error: converting to 'const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[4]; _U2 = const char (&)[4]; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]'
constants.h:1533:1: error: converting to 'const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[9]; _U2 = const char (&)[4]; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]'
constants.h:1533:1: error: converting to 'const std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >' from initializer list would use explicit constructor 'constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[19]; _U2 = const char (&)[4]; <template-parameter-2-3> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = std::__cxx11::basic_string<char>]'
…
Something wrong with constants.h??

And if I modify Makefile:  CPP = clang
Then it seems to be installed successfully, however I can not get the same results with yours in the website.
It seems BSE_Grid_demo.txt can not be read and run as expected. Instead it produces 10 binaries….

*****
Mac OS X  10.12.6
xcode-select version 2347
gcc version 5.4.0 (GCC)
boost: stable 1.62.0 (bottled), HEAD
Python 3.5.2 (default, Oct 11 2016, 04:59:56)
***

Thanks for your patience in advance!

**Comment by FloorBroekgaarden** [comment]
Dear Zhaoyu Zuo, 

Thank you for reaching out. 

If I understand you correctly there are 2 issues:

**1) COMPAS is not compiling when using CPP = gcc. leading to the error message that you copied above.** 

This is a tough issue, but most likely has to do with either the GCC or BOOST library. We have seen similar issues before when compiling COMPAS on a MacOS and some things that helped: 

- indeed using  in the Makefile   `CPP = clang` (or otherwise making sure COMPAS is using the gcc from clang).
**am I correct that this solved the compiling issue for you?** You can double check whether COMPAS compiled correctly by running the command: 

```
(base) Floors-MacBook-Pro:src floorbroekgaarden$ ./COMPAS --help
which returns:
COMPAS v02.09.06
Compact Object Mergers: Population Astrophysics and Statistics
by Team COMPAS (http://compas.science/index.html)
A binary star simulator

Options:
  -h [ --help ]                                                 Print this help message
(...)
```



and secondly by making sure the compiling output was something very similar to: 

```
(base) Floors-MacBook-Pro:src floorbroekgaarden$ make -f Makefile -j 
Building COMPAS with g++
g++ -c -I.  -I/include -Wall -std=c++11 utils.cpp
g++ -c -I.  -I/include -Wall -std=c++11 Options.cpp
g++ -c -I.  -I/include -Wall -std=c++11 Log.cpp
g++ -c -I.  -I/include -Wall -std=c++11 Rand.cpp
g++ -c -I.  -I/include -Wall -std=c++11 Errors.cpp
g++ -c -I.  -I/include -Wall -std=c++11 BaseStar.cpp
g++ -c -I.  -I/include -Wall -std=c++11 Star.cpp
g++ -c -I.  -I/include -Wall -std=c++11 MainSequence.cpp
g++ -c -I.  -I/include -Wall -std=c++11 MS_lte_07.cpp
g++ -c -I.  -I/include -Wall -std=c++11 MS_gt_07.cpp
g++ -c -I.  -I/include -Wall -std=c++11 CH.cpp
g++ -c -I.  -I/include -Wall -std=c++11 GiantBranch.cpp
g++ -c -I.  -I/include -Wall -std=c++11 HG.cpp
g++ -c -I.  -I/include -Wall -std=c++11 FGB.cpp
g++ -c -I.  -I/include -Wall -std=c++11 CHeB.cpp
g++ -c -I.  -I/include -Wall -std=c++11 EAGB.cpp
g++ -c -I.  -I/include -Wall -std=c++11 TPAGB.cpp
g++ -c -I.  -I/include -Wall -std=c++11 HeMS.cpp
g++ -c -I.  -I/include -Wall -std=c++11 HeHG.cpp
g++ -c -I.  -I/include -Wall -std=c++11 HeGB.cpp
g++ -c -I.  -I/include -Wall -std=c++11 HeWD.cpp
g++ -c -I.  -I/include -Wall -std=c++11 COWD.cpp
g++ -c -I.  -I/include -Wall -std=c++11 ONeWD.cpp
g++ -c -I.  -I/include -Wall -std=c++11 NS.cpp
g++ -c -I.  -I/include -Wall -std=c++11 BH.cpp
g++ -c -I.  -I/include -Wall -std=c++11 MR.cpp
g++ -c -I.  -I/include -Wall -std=c++11 AIS.cpp
g++ -c -I.  -I/include -Wall -std=c++11 BinaryConstituentStar.cpp
g++ -c -I.  -I/include -Wall -std=c++11 BaseBinaryStar.cpp
g++ -c -I.  -I/include -Wall -std=c++11 BinaryStar.cpp
g++ -c -I.  -I/include -Wall -std=c++11 main.cpp
utils.cpp Options.cpp Log.cpp Rand.cpp Errors.cpp BaseStar.cpp Star.cpp MainSequence.cpp MS_lte_07.cpp MS_gt_07.cpp CH.cpp GiantBranch.cpp HG.cpp FGB.cpp CHeB.cpp EAGB.cpp TPAGB.cpp HeMS.cpp HeHG.cpp HeGB.cpp HeWD.cpp COWD.cpp ONeWD.cpp NS.cpp BH.cpp MR.cpp AIS.cpp BinaryConstituentStar.cpp BaseBinaryStar.cpp BinaryStar.cpp main.cpp
utils.o Options.o Log.o Rand.o Errors.o BaseStar.o Star.o MainSequence.o MS_lte_07.o MS_gt_07.o CH.o GiantBranch.o HG.o FGB.o CHeB.o EAGB.o TPAGB.o HeMS.o HeHG.o HeGB.o HeWD.o COWD.o ONeWD.o NS.o BH.o MR.o AIS.o BinaryConstituentStar.o BaseBinaryStar.o BinaryStar.o main.o
g++ -o COMPAS utils.o Options.o Log.o Rand.o Errors.o BaseStar.o Star.o MainSequence.o MS_lte_07.o MS_gt_07.o CH.o GiantBranch.o HG.o FGB.o CHeB.o EAGB.o TPAGB.o HeMS.o HeHG.o HeGB.o HeWD.o COWD.o ONeWD.o NS.o BH.o MR.o AIS.o BinaryConstituentStar.o BaseBinaryStar.o BinaryStar.o main.o -I/include -Wall -std=c++11 -L/lib -lgsl -lgslcblas -lstdc++ -lm -lz -ldl -march=k8 -lboost_filesystem -lboost_program_options -lboost_system -std=c++11 -O3
utils.o Options.o Log.o Rand.o Errors.o BaseStar.o Star.o MainSequence.o MS_lte_07.o MS_gt_07.o CH.o GiantBranch.o HG.o FGB.o CHeB.o EAGB.o TPAGB.o HeMS.o HeHG.o HeGB.o HeWD.o COWD.o ONeWD.o NS.o BH.o MR.o AIS.o BinaryConstituentStar.o BaseBinaryStar.o BinaryStar.o main.o

```
To otherwise solve issue (1) (but it seems you managed to compile it) you could try the following things (note that these are just suggestions): 

0) maybe installing a higher version of gcc e.g. gcc 7+
1) you might have to change the line BOOST =    to  BOOST =/opt/local
(especially when you get an error like ld: warning: directory not found for option '-L/lib' - as the location of the BOOST 
 you can check in  /opt/local/lib/ (where your BOOST libraries are). Sometimes the needed libraries in the Makefile like libboost_program_options-mt have or have not the -mt for MacOS. The location of the boost libraries might depend on your MacSystem
3) your compiling seems to use gcc+11, make sure that this is what you want. 

4) you might have to change the std=c++11 to std=c++14 in the LFLAGS and ICFLAGS in the Makefile (clang standard has c++14)
5) make sure your boost and gcc are compiled with the same C++ library (e.g. C++14 and that your gcc is compiled )

see [(https://stackoverflow.com/questions/29542337/undefined-symbols-for-architecture-x86-64-for-boost-c)]
and maybe
[https://solarianprogrammer.com/2018/08/07/compiling-boost-gcc-clang-macos/]


###
**2) Now for the second part of the question:** 
this seems to be an issue  with the reading of the grid parameters in `pythonSubmit.py`, because  the default is namely to run 10 binaries if the BSE grid filename is not given/found. 
Maybe you can check  the following things:

1) the pythonSubmit.py that you are running should have the line grid_filename = 'BSE_Grid_demo.txt' (it is empty by default) 
2) make sure the location of this BSE_Grid_demo.txt file is the demo directory, and especially maybe check whether your COMPAS root directory (i.e. COMPAS_ROOT_DIR ) is set correctly, 

you can check the COMPAS_ROOT_DIR  by running
`(base) Floors-MacBook-Pro:COMPAS floorbroekgaarden$ ls  $COMPAS_ROOT_DIR `

which should show the directories: 
`CompasHPC LICENSE README.md defaults docs postProcessing src`


Let me know if that did/didn't help,  there are definitely some other things that can be tried.. 

Thank you again so much for reaching out! & please feel free to ask any further/follow-up questions - we are more than happy to help 

Floor

**Comment by FloorBroekgaarden** [comment]
Lastly, I add that we are close to having a Docker for COMPAS, that should avoid similar problems with compiling COMPAS.

**Comment by ilyamandel** [comment]
@zuozyu , @FloorBroekgaarden -- if this issue has been addressed, can we close it?

**Comment by zuozyu** [comment]
Dear Ilya Mandel,

Please help close this issue. I didn’t solve the problem according to the suggestion though, I updated 
 to the latest version of macOS, then everything is ok. Thanks.

Best,

Zhaoyu

**Comment by ilyamandel** [comment]
Dear @zuozyu :
I am glad that you've been able to get COMPAS running, and thank you for telling us what worked for you.
Best,
Ilya
