### ISSUE TITLE
Inconsistency COMPAS Default and pythonSubmitDefault parameters

### ISSUE THREAD

**Issue by floriskummer** [TeamCOMPAS/COMPAS#224]
I am not sure if there is a specific reason for this, but I noticed that many of the parameters specified in the pythonSubmitDefault file are different from the default options in COMPAS. I compared the Run_Details files between a run with pythonSubmitDefault and a run with all the COMPAS default values and found inconsistencies for the following parameters:

alwaysStableCaseBBBCFlag
circulariseBinaryDuringMassTransfer 
common-envelope-slope-Kruckow 
forceCaseBBBCStabilityFlag 
initial-mass-max
initial-mass-min 
initial-mass-power 
kick-velocity-sigma-CCSN-BH
kick-velocity-sigma-CCSN-NS 
mass-transfer-fa
mass-transfer-rejuvenation-prescription 
maximum-neutron-star-mass
metallicity
minimum-secondary-mass
pair-instability-supernovae 
pulsar-birth-spin-period-distribution-min 
pulsational-pair-instability 
pulsational-pair-instability-prescription 
semi-major-axis-min 
single-star-mass-max 
single-star-mass-min 
single-star-mass-steps
use-mass-loss

I might haved missed a few

**Comment by ilyamandel** [comment]
Well spotted -- but not sure if it's really a problem.  I think the hard-coded defaults are mostly there so that there is some choice if the user provides none, not necessarily the best choice.  E.g., if tomorrow there's a new measurement of solar metallicity and we all agree that we should switch to using that as a default, we would update pythonSubmitDefault.py, but not the default value in the code provided as a backup in case the user doesn't specify one.
