### ISSUE TITLE
ERRORs when evolving binaries

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#226]
I get quite a few error messages (order of 1% of binaries) that look like

ERROR:  in BaseBinaryStar::EVOLUTION_STATUS BaseBinaryStar::Evolve(): Evolution of current binary stopped, (ObjectId = 91911300)

as well as a few (order of 0.1% of all binaries) that look like 

ERROR:  in BaseBinaryStar::double BaseBinaryStar::CalculateAdaptiveRocheLobeOverFlow(const double): Unexpected Radius increase; After fake mass loss, (ObjectId = 91468659)

when running COMPAS for binary evolution (COMPAS v02.09.10).

Would like to understand where these are coming from and address them better than with the cryptic (particularly in the first case) error message.

**Comment by avigna** [comment]
This has to do with low-mass stars RLOF; they have a convective envelope and therefore expand rather than contract when stripped. Should lead to a CEE/merger. Not very relevant for massive systems, but definitely for low mass star (or stars that become low mass at some point). 
Previosly I had some printing staments attached to them, but most printing statements have been removed during rewriting.
I think the easier/right thing is to have them experience a CEE.

**Comment by ilyamandel** [comment]
@avigna -- are both errors mentioned above caused by the expansion of low-mass stars during RLOF, or just the second one?

**Comment by jeffriley** [comment]
@ilyamandel @avigna Just the second.  The first:

    ERROR: in BaseBinaryStar::EVOLUTION_STATUS BaseBinaryStar::Evolve(): Evolution of current binary stopped, (ObjectId = 91911300)

maybe shouldn't be labelled "ERROR".  It is an informative message to let the user know that the evolution of the binary was stopped.  This can happen for two reasons:

    1. The maxmimum number of timesteps was reached (default is 99999)
    2. The binary formed a DCO

In the second cased (DCO formation), the error message will have the string:

    ": Double compact object"

appended.

Since that string is not present in the error message you supplied, you were seeing case 1 (maximum timesteps)

**Comment by ilyamandel** [comment]
Thank you!  I'd still like to understand why we reach the maximum number of time steps, and it sounds like we should fix issue 2, so I am going to leave this open for now.

**Comment by ilyamandel** [comment]
This issue has been fixed with the latest changes to adaptive mass transfer, step sizes, etc., so closing it.
