### ISSUE TITLE
Incorrect fitting parameters in Muller 16 SN kick function

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#229]
In BaseStar.cpp +2791-2801

The constants in the function don't line up with those reported in Vigna-Gomez 2018 (eq. B5). 

The piecewise ranges on m_CO are mostly* correct, but the constants that determine the kick in the code are double what they are in the paper (except for line 2794, which has a 250, where 200 would be the appropriate double). I'm not sure why this is, but it seems like a bug.

*Somewhat related, the lowest limit in both (B4) and (B5) in the paper is m_CO = 1.372 (below which there is no SN), but in the code, we have m_CO < 1.44 statements instead (GiantBranch.cpp +1170 has the analogous lower limit for remnant mass). Alejandro comments that this lower limit is a first approach, so this may be a feature.

**Comment by avigna** [comment]
This indeed seems to be a bug/inconsistency. There was a `dampingFactor = 2` which I seem not to have included in COMPAS. This was since Legacy and propagated to refactored. This likely means that the Muller+2016 kick results from Vigna-Gomez+2018 have an increased kick by a factor of 2 (with likely more disruptions).  Working on updating this to reflect what is on Appendix B of Vigna-Gomez+2018.

Side note: this remnant mass and natal kick implementation might be deprecated, but that is a different point.

**Comment by ilyamandel** [comment]
This has been fixed by @avigna in  #310 , closing.
