### ISSUE TITLE
The Helium core mass can exceed the total mass for massive SSE stars

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#234]
Plotting
STAR_PROPERTY::HE_CORE_MASS -  STAR_PROPERTY::MASS
at the penultimate timestep as a function of ZAMS mass.

SSE evolution with COMPAS v02.10.03

![Hevstotal](https://user-images.githubusercontent.com/512213/79527234-65dd0280-80aa-11ea-9901-dfff48fbf769.png)

zooming in:

![Hevstotalzoom](https://user-images.githubusercontent.com/512213/79527241-6c6b7a00-80aa-11ea-94d0-7058ca1fbe05.png)

**Comment by SimonStevenson** [comment]
Do you really mean the helium core mass exceeds the total mass of the star? Shouldn't your y-axis be positive in that case? That is certaintly what I am finding any way.

Either way, I guess they should both be identical at this stage of evolution (for evolved helium stars, type 8), since:
CalculateHeCoreMassOnPhase(){ return m_Mass; }         

I think this must be due to the order of operations, and that the helium core mass lags one timestep behind the total mass (i.e. that we update the helium core mass, and then apply wind mass loss to the star afterwards, and then print). This is supported by:

[for a MZAMS=40Msol star]

HeCoreMassMinusTotalMass[isHeHG]
array([0.0318 , 0.03197, 0.03183, 0.03171, 0.03159, 0.03147, 0.03136,
       0.03123, 0.03113, 0.03101])

np.diff(data['Mass'][isHeHG])
array([-0.03197, -0.03183, -0.03171, -0.03159, -0.03147, -0.03136,
       -0.03123, -0.03113, -0.03101])

These are identical, supporting that the helium core mass is lagging by one timestep, and the magnitude of the difference is just the helium star wind mass loss in one timestep. 

Possible solution?
- For helium stars, (re)calculate helium core mass after applying wind mass loss?

Any thoughts on the order of operation @jeffriley?

**Comment by SimonStevenson** [comment]
(PS before you say it, I'm sure that the order of operations is the same as in Legacy COMPAS :) )

**Comment by ilyamandel** [comment]
Yes, I had mislabeled the axes, sorry, but the He mass was indeed larger than the core mass for stripped stars.  And yes, I agree with @SimonStevenson 's finding that the indices are one off: the He core mass is equal to the total mass of the star one step earlier for HeMS and HeHG stars.   Nice sleuthing, @SimonStevenson !

**Comment by jeffriley** [comment]
> (PS before you say it, I'm sure that the order of operations is the same as in Legacy COMPAS :) )

Well... that wasn't what I was going to say :-)  Maybe it isn't.  Does it only happen for HeMS and HeHG stars?  If so, why not HeGB stars?  The operations should all happen in the same order (in EvolveOnPhase() and ResolveEndOfPhase()) but maybe they didn't in the legacy code - for a reason.  

I do remember when I was refactoring that there were instances where I thought things happened out of order, and I wondered then if forcing them all into the same order for all stellar types might cause problems - maybe this is one of those instances.

**Comment by jeffriley** [comment]
Having said that, I thought I checked when refactoring that any reordering of calculations was benign, but maybe I missed something.

**Comment by SimonStevenson** [comment]
I haven't checked for other types, but I would guess it happens for all helium stars.

**Comment by jeffriley** [comment]
This is seen in the detailed output file?  If so, it may just be where we are printing the detailed output record.  I did add a few locations in an effort to pick up stellar type changes - sometimes we would miss a stellar type change in the detailed output file if stellar type changed very quickly.  Although I would have thought all required calculations would have been done in the BaseStar code before printing in the BaseBinaryStar code.

Does this happen all the time or do I need a pythonSubmit file to duplicate it?

**Comment by SimonStevenson** [comment]
Yeah you should see this in the detailed output for any massive (mzams > 40 Msol) single star.

**Comment by jeffriley** [comment]
Ah, so that's in the SSE output file.  That's only printed in one place, so ignore my comments about the detailed output file - I thought this was in the context of BSE

**Comment by SimonStevenson** [comment]
Another possible 'solution' could be that when we remove mass from a star, we check if that star is a helium star, and if so, we remove the same amount of mass from both the total mass and the helium core mass.

**Comment by jeffriley** [comment]
Maybe.  I think we should first try to figure out why the values seem to be offset by one timestep.  I'll take a look over the weekend if you like.

**Comment by jeffriley** [comment]
The problem is that we calculate the properties of the star for the current timestep (radius, luminosity, HeCoreMass, COCoreMass etc.), then we resolve mass loss via winds, then we print the properties.  For this problem in particular (He core mass exceeds total mass) we see a problem because for helium stars the He core mass is just the total mass, so when we calculate the properties of the star we set m_HeCoreMass = m_Mass, but then we apply winds mass loss, which only changes m_Mass, before we print the properties.  If the star loses mass due to winds m_Mass is reduced before we print the properties but m_HeCoreMass is still at the pre-winds value.

This is also true in the legacy code.  No, I am not pointing that out to assign blame - I looked there to see if legacy exhibited the problem, and if it did not I would change v2 to match the legacy code.

So the question is whether we should resolve winds mass loss before calculating the other (other than mass) properties of the star (problematic for the first timestep), or whether we should adjust all the mass properties (HeCoreMass, COCoreMass, massEnv etc.) as appropriate when we resolve winds mass loss (but then those properties will have been calculated at a different time effectively from properties such as radius and luminosity I think).  Which value of m_Mass should we use to calculate the other properties of the star?  

I think it comes down to what is it we think we are printing on each output record.  At the moment we are printing the values for properties of the star calculated using the mass before winds loss, but the mass after winds loss - so values effectively at different times in the star's evolution (albeit not by much - some values are calculated at the start of the timestep, while mass is calculated at the end of the timestep and is not the value used to calculate the other properties).

**Comment by jeffriley** [comment]
I think the solution is to resolve winds mass loss at the start of the timestep before calculating other properties, but it should be resolved using the duration of the previous timestep.  For the first timestep we would use a value of zero for the duration of the previous timestep, so no winds mass loss in the first timestep.

**Comment by jeffriley** [comment]
Note that the fix described above only affects SSE.  The BSE code doesn't call the Star::EvolveOneTimestep() to evolve the constituent stars (except to calculate the timestep, and the results of those calls are discarded).  BSE code applies winds mass loss separately, and may exhibit the same problem as addressed by this issue - we should probably check that.

**Comment by ilyamandel** [comment]
@jeffriley -- the issue is fundamentally that we are converting a differential equation into a difference equation.  If the tilmestep is small enough, then before/after are sufficiently close together that it doesn't make much difference which is used.  The only caveat is that when printing, I think we should print consistent values for all properties -- it's awkward if some have the "before" values and some have the "after" values.  I think the solution here, however, is not to move the wind mass loss around, but simply to update the He core mass whenever the mass is updated for stripped stars.  This way, the problem will be fixed for both SSE and BSE in one place.

**Comment by jeffriley** [comment]
@ilyamandel understand - will that work when the timestep is large?  We plan to (at some stage) change the timestep calculation - is that going to be a problem?  We also need to look at BSE - I think we probably do the same thing there (i.e. calculate a bunch of stuff, then apply mass loss, so the mass we print in the output files will be reduced whereas He core mass etc. probably won't be).

Anyway, the root cause is now known - I'll leave it to @SimonStevenson to figure out what the best fix is since this is assigned to him.

**Comment by jeffriley** [comment]
Sorry, I missed this:

> This way, the problem will be fixed for both SSE and BSE in one place.

Not sure that is possible given that winds mass loss is applied separately and in different places for SSE and BSE.

**Comment by ilyamandel** [comment]
@jeffriley -- exactly, so I think all masses should be adjusted in the winds function (which is the same, right?), not the EvolveOneTimestep function, which is different...  But maybe I need to check the code again. :)

**Comment by ilyamandel** [comment]
And the time step should never be too large -- that's the point of our adaptive time step checks, to ensure convergence.

**Comment by jeffriley** [comment]
> so I think all masses should be adjusted in the winds function (which is the same, right?)

No, they're different.  Wouldn't we also need to update for mass transfer for BSE?

> And the time step should never be too large -- that's the point of our adaptive time step checks, to ensure convergence.

Ok.  It just feels like a kludge rather than a proper fix to me, but I'll defer to you and Simon...

**Comment by SimonStevenson** [comment]
I just evolved a wide binary where the primary star was the same as the single star I was using to debug above (40 Msol, solar metallicity, output file attached). This issue does not appear to be present for binaries, i.e. I get

`
data['Mass_1'][isHeMS] == data['Mass_He_Core_1'][isHeMS]
data['Mass_1'][isHeHG] == data['Mass_He_Core_1'][isHeHG]
HeCoreMassMinusTotalMass = data['Mass_He_Core_1'] - data['Mass_1']
print(HeCoreMassMinusTotalMass[isHeMS])
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
print(HeCoreMassMinusTotalMass[isHeHG])
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
`

I also noticed that the final mass of the star is different at the 2nd decimal place in the two cases

[BSE_Detailed_Output_0.txt](https://github.com/TeamCOMPAS/COMPAS/files/4537563/BSE_Detailed_Output_0.txt)

**Comment by SimonStevenson** [comment]
Is there a way we can make the code path for single stars and binaries fundamentally more similar than they currently are? I realise this may be a larger amount of work than a simple fix for this issue, but it seems there may be many issues where things work differently for binaries and single stars. This will also be useful (essential?) for properly evolving merger products (binary creating a single star, see #209 ).

**Comment by jeffriley** [comment]
They're not really that dissimilar.  The big differences that come to mind easily are:

(a) the timestep is calculated differently for single stars and binary stars
(b) the mass loss due to winds is calculated differently
(c) mass transfer

I'm not sure how to reconcile those between SSE and BSE to the point that we have a single(ish) code path.  I think we probably could, but it would take a bit of a shift in the approach currently taken.  I think we'd have to do something like evolve each star separately but take into account that it is in the presence of a companion rather than evolve a binary star that has two constituents - if that makes sense.  We'd evolve one star for one timestep, then the next star for one timestep, etc.  I think provided we could work out the timestepping issue maybe that is not too far different from what happens now.  How to reconcile common envelopes...?  I think we could do it, it might just take a bit of thinking about.

If this issue is not evident for binary stars, then we must either be printing the mass value before mass loss/transfer is applied, or the other mass values are recalculate after mass loss/transfer.

We could just print the values before mass loss is applied in SSE - which is what I was getting at when I suggested we apply mass loss for one timestep at the start of the next - so the amount of mass loss is calculated in one timestep, but not actually applied until the start of the next timestep.

**Comment by jeffriley** [comment]
> We'd evolve one star for one timestep, then the next star for one timestep, etc. 

We'd still have to do that in the context of a binary star of course.

> Is there a way we can make the code path for single stars and binaries fundamentally more similar than they currently are?

Maybe not actually...  As I said above, they're not that dissimilar.  There are things that we have to do for binaries because they're binaries, but other than that I think they are fairly similar.  Maybe I need to understand better what you want more similar...

**Comment by ilyamandel** [comment]
I am with @SimonStevenson  on this.  I would like to be able to use single-stellar evolution to check and debug certain aspects of binary evolution that apply to single stars (e.g., winds or supernova remnants), but it seems that the code paths are often too different to make this possible.  What if we think of single star evolution as just a binary with a primary that is the single star of interest and a very distant point-mass companion that never interacts with the primary, and doesn't need any computational cycles to evolve it [say it's a black hole with a mass of zero located at infinity, so it just sits in place and does nothing forever]?  That's a hack, of course, but at least it will mean that single stars behave exactly like binaries in terms of the code path.

**Comment by jeffriley** [comment]
>  it seems that the code paths are often too different to make this possible

I don't think they are that different.  All the Hurley equations are in SSE and BSE calls that code.  I assume you're talking about a really wide binary and a single star - so that the binary-specific stuff doesn't affect it too much?

What's different at the moment that applies to single stars (that I can think of):

(a) timestep calculation
(b) winds mass loss

Supernova kicks are now in SSE.

Theoretically if we make (a) and (b) the same, then if the stars are widely separated and so don't really interact that much, I think the code paths are pretty close.

Can we make (a) the same?  I don't know - why is it different?  If the timestep won't be the same then you probably can't check one against the other easily.

Can we make (b) the same.  Again,  I don't know - why is it different?  I think the mass loss rate calculation is different, but I could be mis-remembering - and if it is maybe if the stars are really wide it shouldn't be.

So, again, what is really that different?  I don't think it is that much.  Whatever it is, can we make it the same? 

I we run a single star through SSE, and then run a single, really wide, binary with stars of the same mass, and compare the SSE output with the detailed output, what is it that is significantly different?  Have we checked?

**Comment by ilyamandel** [comment]
This is still an issue even after the latest PR, but I know that internally, the He mass does not exceed the total mass.  So, it's an issue in printing.  To be fixed next week. :)

**Comment by ilyamandel** [comment]
Issue has been fixed by the latest PRs (I just messed up checking yesterday :) ).  Closing.
