### ISSUE TITLE
Expanded grids: single parameters

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#244]
**Is your feature request related to a problem? Please describe.**
Not a problem, just 2 related features that I think would be useful in the future.

**Describe the solution you'd like**
I would like to have grids implemented with the flexibility such that a) if a parameter is not included, COMPAS has a default distribution for that parameter, and b) any compas parameter can be specified. 

a) In my particular case, I'm trying to input specific values for only the kick_velocity_1. I am not concerned about the other grid parameters (only that they be reasonable), but currently I need to include all the other initial parameters (masses, separation, etc.) as well as the other SN kick parameters. Ideally, I would make a grid of just the parameter(s) of interest to me, and everything that is not in the grid file falls back to a default.

b) I would also like to have other choices of parameters which can be read in from a gridfile. In my case, I would like to be able to directly specify the remnant mass, but I can see why any other parameter would be usefully specified here as well. 

**Describe alternatives you've considered**
Working with the current grid files is fine for feature (a), it's not really that much of a problem to specify all the other parameter distributions (I just leave them as is from the stroopwafel grid file creator). Feature (b), I'm not sure what the alternative would be, happy to hear suggestions.

**Comment by jeffriley** [comment]
Is (a) something better done outside of COMPAS?  I think @FloorBroekgaarden talked about scripts to build grid files.  If we do it inside COMPAS then someone will surely ask that we allow the specification of which distributions to use as the defaults...  Whereas if we provide scripts to build grid file outside of COMPS then the user can choose whatever distributions they want.

I think (b) is a good idea, at least for things that can currently be specified at the start of the COMPAS run.  Specifying the remnant mass (and other properties that are calculated rather than specified) would need some additional coding I think, so might need some more thought.

**Comment by FloorBroekgaarden** [comment]
Yeah, For (a) @lokiysh will soon release a script that makes it easy to specify which parameters are constant. It is being tested at the moment.

**Comment by lokiysh** [comment]
I think @reinhold-willcox is already using that. And it can easily be used, at its current state, to include more parameters (for example remnant mass) provided COMPAS allows those parameters.

**Comment by FloorBroekgaarden** [comment]
perfect! Thanks @lokiysh

**Comment by reinhold-willcox** [comment]
Closing, because part (a) is unique to me (and I have a local branch that solves it), and (b) is known and referenced in other issues.
