### ISSUE TITLE
Implement supernova output for SSE

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#253]
**Is your feature request related to a problem? Please describe.**
For binaries, we have several summary outputs that summarise supernovae, common envelope episodes and double compact object binaries. Most of these don't make sense for single stars, so we don't have them, but a file tracking all supernovae that occur in a population of single stars would make sense.

**Describe the solution you'd like**
Implement supernova output for SSE

**Describe alternatives you've considered**
In principle, all of the data is available in the detailed outputs, but this would be a useful data product.

**Additional context**
NA

**Comment by jeffriley** [comment]
@SimonStevenson @reinhold-willcox Have either of you done anything with this?  I'm doing some work on the logging code and I could implement the SSE supernova output as part of that.  Let me know if you want me to do it, and if you want to provide a list of attributes to include in the file.

**Comment by SimonStevenson** [comment]
No sorry Jeff I haven't looked at this. If it would fit naturally with the restructuring you are doing, then that would be great.

I guess we want all of the parameters from the normal supernova file that make sense for a single star. I think that is:
ID     	    SEED    	Drawn_Kick_Velocity_SN	Applied_Kick_Velocity_SN	Fallback_Fraction_SN	SN_Kick_Theta_SN	SN_Kick_Phi_SN	SN_Type_SN	Mass_Total@CO_SN     Mass_CO_Core@CO_SN	   Mass_SN    		Stellar_Type_SN	Supernova_State	Stellar_Type_Prev_SN	Mass_Core@CO_SN	Mass_He_Core@CO_SN	      Time      	Systemic_Velocity	Hydrogen_Rich_SN	Hydrogen_Poor_SN

**Comment by reinhold-willcox** [comment]
Haven't looked at this, thanks for taking it over Jeff!

**Comment by jeffriley** [comment]
When I offered to do this I was comfortable in the knowledge it would take me a bout 30 minutes.  The logging code was written so t hat adding new log files entails specifying what columns are required (just a list of attributes), and writing a couple of 1-line wrapper functions that call the logging functions.  Then it's just a mtter of putting the function calls in the right place in the code, and voila! you're done.  And that's all it took.  Then I looked inside the SSE Supernova file I created.  Each star had multiple entries - some in double-digits.  That didn't seem reasonable.  I put the call to the print function in (the infamous!) GiantBranch::ResolveSupernova(), and inside the check to determine the star is considered to be a supernova.  How could that be being called multiple times?  I'm glad you asked...  In Star::EvolveOneTimestep() we save a copy of the star, evolve it a timestep, and if we don't like how much change happened during the timestep we revert to the previous state, reduce the timestep and try again.  Guess how many times we revert the state of the star?  Oh a few - and some in double-digits.  In fact, as many times as there were entries for each star in the SSE Supernova file - minus 1 (the last one was the one, and the only one, we really wanted to see in the file).  We can't just print the values after we've decided to accept the timestep and not revert - they might have changed since the moment of the supernova...  The solution was to squirrel away the values at the time of the supernova and print them later - after we've decided to accept the timestep and not revert.  Sounds simple when I write it like that.  12 hours of coding later I'm done!  The SSE Supernova file and supporting code is in v02.15.00.

@SimonStevenson I think I added all the attributes you suggested, except SN Supernova_State - I think that's for binaries only.

See pull request https://github.com/TeamCOMPAS/COMPAS/pull/360

**Comment by SimonStevenson** [comment]
haha oh no I think we've all been there. Sorry that this was such a pain, and thanks for doing this!

**Comment by reinhold-willcox** [comment]
oof, sorry to hear it Jeff.

That brings up an interesting point though about the number of evolves and reverts the star is going through though...

**Comment by jeffriley** [comment]
Indeed - that probably means we should look at implementing a better, adaptive, timestep mechanism

**Comment by jeffriley** [comment]
Implemented in v02.15.00
