### ISSUE TITLE
CE accreted onto BHs when using  metallicities < 10^-4 

### ISSUE THREAD

**Issue by LiekeVanSon** [TeamCOMPAS/COMPAS#304]
**Describe the bug**
When running COMPAS with default settings but very low metallicities (below 10^-4) some BHs are seen to accrete the complete envelope of the companion during a CE event, even though  common-envelope-mass-accretion-prescription = 'ZERO',  and eddington-accretion-factor = 1.
This results in merging BBHs with primary BH masses up to 80 Msun.

**Label the issue**
urgency_low, severity_major

**To Reproduce**
1. Unzip attached file "GridListAndPythonSubmit.zip"
[GridListAndPythonSubmit.zip](https://github.com/TeamCOMPAS/COMPAS/files/4983234/GridListAndPythonSubmit.zip)

2. run the supplied **pythonSubmitDetailed.py** (which points to the supplied grid **MassiveBH_grid.txt**) to get detailed output (also used for plotting detailed evolution of images attached att screenshots)

3. Complete list of BBH systems with M_primary> 40 Msun can be found in **buggy_BBHs.txt.** A corresponding gid file to run these systems in detail can be found in **buggy_BBH_gridParams.txt**
!! Since these systems were run using Stroopwafel, it's difficult to recreate them based on the SEED. Sampling distributions are supplied as addtional content.

**Expected behavior**
BH's should NOT accrete mass during the CE-phase

**Screenshots**
Detailed evolution track of the first 3 samples from MassiveBH_grid.txt
![80000594](https://user-images.githubusercontent.com/57514659/88568538-6be36780-d039-11ea-9704-098a6a7dedce.jpg)
![80000842](https://user-images.githubusercontent.com/57514659/88568543-6c7bfe00-d039-11ea-8706-6002474ae269.jpg)
![170000742](https://user-images.githubusercontent.com/57514659/88568548-6d149480-d039-11ea-9d67-ef0f3cd3e3d5.jpg)

**Versioning (please complete the following information):**
 - OS: MacOS Cattalina [v10.15.5]
 - COMPAS [v02.10.03]

**Additional context**
COMPAS run details of simulation
[Run_Details.zip](https://github.com/TeamCOMPAS/COMPAS/files/4983272/Run_Details.zip)
[distributions.csv.zip](https://github.com/TeamCOMPAS/COMPAS/files/4983291/distributions.csv.zip)

**Comment by ilyamandel** [comment]
Hi @LiekeVanSon ,

OK, this one is tricky.  First, I don't think accretion is happening during the CE itself, I think these systems have immediate post-CE RLOF (can you check if Immediate_RLOF>CE flag is 1 )?

Second, we sort of have a cheat for mass transfer efficiency, and you discovered it.  We ask for the rate at which mass can be donated and the rate at which mass can be accepted, and the ratio of the latter to the former is the mass transfer efficiency.  We don't trust our duration of mass transfer enough (we don't resolve the mass transfer details), so if we say that the donor should donate a total mass dM and the accretor can accept a fraction fa of it, the accretor's mass goes up by dM*fa -- that's it.  Most of the time, that's just fine, although the result may look odd because of the artificial appearance that the mass transfer happens in a short time step. 

But I suspect that one of the unphysical things about Z<0.0001 stars (which we know COMPAS doesn't handle properly) is that they have unphysical thermal timescales, so that fa = 1 even though the Eddington limit is correctly applied.  

So the right solution is, I believe, to prevent COMPAS from running with Z<0.0001, where the models are clearly unphysical.  I'll close this issue and start a new issue shortly.

**Comment by ilyamandel** [comment]
Closing this one, see #308 instead.

**Comment by LiekeVanSon** [comment]
Hi Ilya,

Thanks for checking!
The Immediate_RLOF>CE =1 should have been filtered out in my sample.

Good to keep in mind that this is how COMPAS treats mass transfer!

I agree that promting an error when Z<10^-4 is used seems like the best solution.

Cheers Lieke
________________________________
