### ISSUE TITLE
Consistent use of tabs and spaces

### ISSUE THREAD

**Issue by warrickball** [TeamCOMPAS/COMPAS#318]
I've finally gotten around to downloading COMPAS and running the demo. It all worked as described (Fedora 32) without modifying the Makefile at all because I think `boost` and `gsl` are installed into default system-wide include paths anyway.

I couldn't help but have a quick look at the source and, though I don't really know C++, I started getting confused by indentation, which is variously done using tabs and spaces. You can find examples with e.g. `sed -n '/\t/p' $COMPAS_ROOT_DIR/src/*.cpp`. This is only cosmetic but it makes it slightly more difficult to read (and therefore interpret) the source.

If someone tells me what the preferred scheme is, I'm happy to open a PR some time. e.g. should indentation always be 4 spaces or always tabs? I don't have a strong opinion on which is used but I think mixing them is widely regarded as undesirable.

**Comment by ilyamandel** [comment]
Hi @warrickball ,

It's great to hear from you!  Hurray!  Glad that everything worked for you and ran out of the box!

I suspect I may be at least partly responsible for the spaces vs. tabs issue (as in, I know I've been inconsistent).   @jeffriley -- what do you prefer?

**Comment by jeffriley** [comment]
I prefer the way I did it when I refactored :-)  I agree whatever we choose we should be consistent, but that's hard to achieve with many developers all from different backgrounds.  I did put some style guidelines in the documentation.  Here are some of my preferences that I may or may not have put in the documentation:

- tabs for indentation (but could live with spaces) - as long as whether tabs or space are used the indentation size is 4 columns.

- spaces around arithmetic operators, and err on t he side or more brackets (e.g. a = ((2 + 3) / 4) * (3 / 2).  I think the spaces makes it easier to read the equation, and brackets make it easier to interpret.  There is no downside in having more brackets - the parser handles them without trouble...

- braces on the same line as the 'if' etc. (this is K&R style - I did put that in the documentation, and I'm pretty fixed on that one (you wouldn't believe the angst this generates among programmers...)

- I tried (failed in some cases) to name functions so that the name indicates what it does - especially start with "Calculate" if the function actually calculates something.  

- class member variables should start with "m_" (to indicate they are class member variables).  I used "p_" for parameters, so that they are easily identifiable as parameters rather than local variables or class member variables.

- local variable names should be camelCase, beginning with a lowercase letter - with the caveat that sometimes, for well-known names or words that are always written in uppercase, uppercase might be used, and that it should look good :-)  Common sense should prevail...  (I would use "WRfactor" rather than "WRFactor" - just because it delineates the words better (imo))

We should one day review function and variable names...

Anyway, just some quick thoughts.  Since more people are now starting to dive into the code we probably should produce at least a basic style guide.

**Comment by warrickball** [comment]
> * tabs for indentation (but could live with spaces) - as long as whether tabs or space are used the indentation size is 4 columns.

But the reader gets to decide how big a tab is while they read the code. After a quick glance, I'd say the current tabs are intended to be 4 characters but I use a different default because I work on code that forbids tabs, so I like to be able to see them quickly. In other words, I could make the code look OK to me by changing the tab-width to 4 characters. Maybe that closes the issue?

That said, there are also tabs that don't appear to be for indentation. e.g. line 106 of `CHeB.cpp` is:
````cpp
<TAB>return<TAB>lambdaCE;
````
The second tab strikes me as bad style by most style guides. I can see similar things in `BinaryConstituentStar.cpp` at lines 341, 342 and 371. I haven't looked any further but I imagine there are more.

**Comment by jeffriley** [comment]
> I'd say the current tabs are intended to be 4 characters

I believe they are - that's my preference.

> <TAB>return<TAB>lambdaCE;

That shouldn't be like that.  feel free to change anything you see like that

> ...by most style guides

The trouble is choosing one everyone likes and will stick to.

You could always either find or write a code prettifier...

**Comment by warrickball** [comment]
Ah, I've just looked at the *Indentation* section in the documentation and I now see that this is a known issue and that the docs do say that indentation is 4 spaces, which can reasonably be intepreted as "set tabs to 4 spaces". I'll have a look for the non-indenting spaces and maybe open a PR.
