### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#320]
Currently, errors and warnings are reported in text outputs, but evolution continues, potentially with unpredictable results.  There is even a risk that evolution could go into an infinite loop.  Throwing and catching COMPAS exceptions, ultimately leading to a termination of evolution, could be a safer mechanism for error handling.

**Comment by ilyamandel** [comment]
@jeffriley -- are we realistically going to try exception handling, or does this belong in the "won't fix" bin?

**Comment by jeffriley** [comment]
It's a big job...

A few things:

> Currently, errors and warnings are reported in text outputs, but evolution continues, potentially with unpredictable results. 

That's true.  Do we have a good idea of what we should actually do with those errors and warnings?  The classification of error vs warning was mine when I refactored the code, and I knew a lot less then about what was going on than I do now, but still I think someone with more experience/knowledge could classify them better - then we could (e.g.) fail (stop) on error and continue on warnings (as a first cut).

> There is even a risk that evolution could go into an infinite loop

Possible, but I think unlikely - I think I fixed every place in the code that could do that.

> Throwing and catching COMPAS exceptions, ultimately leading to a termination of evolution, could be a safer mechanism for error handling

That's true.  The trouble is we would have to check every calculation for (e.g.) divide by zero, and throw an exception for that.  That's not only a performance issue, we either have to fail on every exception, or sit down and work out which ones are fatal and which ones should just be warnings.  

Would be terminate the evolution of a singe star/binary, and continue the rest (from --number-of-systems, or a grid file), or would we terminate the entire run since the run might be dependent upon having all stars/binaries evolved (or should that be configurable)?

As I said, a big job - even just figuring out how we want to handle different errors/warnings - but ultimately it would make the product better.

**Comment by ilyamandel** [comment]
OK, leaving this alive for the future at @jeffriley 's suggestion.

**Comment by jeffriley** [comment]
Closing for now - will revisit later.

**Comment by ilyamandel** [comment]
I did look at this one as part of my PR and issue review, but intentionally didn't even ask. ;-)
