### ISSUE TITLE
Function name clarification

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#345]
We have several function names in the code that are repeated across different classes (without an inheritance relationship) and do different things.  An example is BaseStar::ResolveSupernova() and BaseBinaryStar::ResolveSupernova().  The former resolves the supernova for a single star: changes the mass, stellar type, assigns a natal kick, etc.  The latter updates the binary’s orbital properties in response to a SN.  Therefore, to avoid confusion (e.g., I personally mistakenly thought that the stellar type would change to a compact remnant in BaseBinaryStar::ResolveSupernova() ), I propose to change the function name to UpdateOrbitAfterSupernova() in the latter case, which is a clearer descriptor for what the function does and leaves less opportunity for confusion.

**Comment by jeffriley** [comment]
My thoughts.  Grab a coffee 😊 

On the specific function mentioned here (BaseBinaryStar::ResolveSupernova()), I think there should be a function BaseBinaryStar::ResolveSupernova(), as well as BaseStar::ResolveSupernova().

What I was trying to do with BaseBinaryStar::ResolveSupernova() was have that function do everything that needs to be done, for the binary, in the event one of the stars undergoes a supernova event.  It may be that all that function does at the moment is update the orbit - I don't think it is (I think it does a little bit of housekeeping as well), but let's assume that it is, and let's further assume that updating the orbit is all that needs to be done when one of the stars undergoes a supernova event. I agree completely with Ilya that function names should describe what the function is doing.  I think what we’re trying to do at this point in the code is resolve a supernova event, and that’s why I think the function should be called ‘ResolveSupernova’. It may be that the ‘ResolveSupernova’ function should do whatever housekeeping that needs to be done, and then call a new function named UpdateOrbitAfterSupernova() (or whatever order is most appropriate), but I think we should keep BaseBinaryStar::ResolveSupernova() – that way we have a function whose job it is to resolve a supernova event, and it is that function, and only that function, that needs to know how to do that (which might just be update the orbit and do some housekeeping).  The point is that we really should be trying to encapsulate functionality into high-level functions whose job it is to do these things (whatever they might be). We might find later that we need to do something else – something in addition to updating the orbit – to resolve a supernova.  If we have a high-level function whose job it is to resolve supernova events, then we know where we need to put that new piece of code.

The same is true for BaseStar::ResolveSupernova(), for the same reasons.  Naturally, since what we need to do to resolve a supernova in the context of SSE is different from what we need to do to resolve a supernova in the context of BSE, the functions will do different things – but their overall task is to resolve a supernova event.  If we have them and we need to change how we resolve supernova events in the context of either SSE or BSE, we know where to go to change the code.  Each of those functions could – probably would – call other, lower-level, functions to do the work, but the high-level function should be where the task is orchestrated.

To Ilya’s comment:

> We have several function names in the code that are repeated across different classes (without an inheritance relationship) and do different things

The reference to “without an inheritance relationship” recognises that functions derived from a virtual function in an inheritance chain are required to have the same signature – otherwise the inheritance fails.

But Ilya is suggesting that we shouldn’t have functions in multiple classes with the same name because it causes confusion.  I don’t think that’s necessarily true (in fact, I think that having functions with similar high-level goals named differently in different classes could be confusing).

First though, I think the assertion “… and do different things”, especially with respect to BaseBinaryStar::ResolveSupernova() and BaseStar::ResolveSupernova(), is actually not right.  Given what I have described above, I think those functions actually do the same thing (or should – maybe I didn’t get the implementation quite right) – they both (are supposed to) resolve a supernova event.  The fact that they perform different subtasks to achieve the overall goal of resolving a supernova event is completely expected in the OO paradigm – they are resolving a supernova event in their own context: SSE or BSE.

It is important to understand that the two functions in question here are not actually named the same – I think this might be at the heart of the problem. Their actual names are BaseStar::ResolveSupernova and BaseBinaryStar::ResolveSupernova, and if they are being confused it is because we’re not completely in tune with the OO paradigm – we don’t yet grok it.

If a reader is looking at code in the BaseBinaryStar class, and sees a call to the ResolveSupernova() function, then it is the BaseBinaryStar::ResolveSupernova() function.  This is not ambiguous, and shouldn’t be confusing. The compiler allows developers to use a bit of shorthand there – they can omit "BaseBinaryStar::" if the code is in a class member function of the BaseBinaryStar class (or in the header file for the class).  If the developer actually wanted to call BaseStar::ResolveSupernova() from the BaseBinaryStar class then the function name would need to be fully specified.  There are two (main) ways to call, say, BaseStar::ResolveSupernova() function from the BaseBinaryStar class.  The first is by calling the fully-specified function BaseStar::ResolveSupernova().  To do that though, the BaseStar::ResolveSupernova() function would have to be a static function (because here it would be being called without an object that would provide context for the BaseStar class member variables).  To call a non-static function (which BaseStar::ResolveSupernova is), the developer would need to have declared a BaseStar object and call BaseStar::ResolveSupernova() using that object (either object->ResolveSupernova() or object.ResolveSupernova()).  An undecorated call to ResolveSupernova() in code within the BaseBinaryStar class is, by definition, to BaseBinaryStar::ResolveSupernova.  To be a call to a function in any other class it would need to be fully-specified.  There should be no ambiguity or confusion.

From Ilya’s comment:

> I personally mistakenly thought that the stellar type would change to a compact remnant in BaseBinaryStar::ResolveSupernova()

Well, I would have thought that a binary would be prompted to resolve a supernova event because it noticed (or was notified) that one of its constituent stars had undergone a supernova event, and that would imply that the stellar type had already changed.  But that could be because I wrote the function (and bear in mind that I wrote it at a time that I understood the process far less well than I do now, and I don’t consider myself even close to an expert now…), so I defer here to Ilya’s knowledge of the process and what the expectations of someone reading the code might be.  But, in a well-written OO program, code in the BaseBinaryStar class would not change the value of variables in the BaseStar class (i.e. the stellar type) – at best the BaseBinaryStar code could inform the BaseStar code of some event or change in environment, and the BaseStar code would change its member variables accordingly.  My point is, if the stellar type was to change in the BaseBinaryStar::ResolveSupernova() function, it could (or should) only be by informing the constituent stars of some change in their environment and letting them determine how to react to that change.  And that could have happened in the BaseBinaryStar::ResolveSupernova() function – but I refer to my first point here: the way I wrote the function we are resolving a supernova event that we have been informed has occurred in one of our constituent stars (has occurred – so t he stellar type has already changed).  I don’t know how else we could do that – why would we want to update the orbit of the binary after a supernova event unless we had information that the supernova event had occurred?  The supernova event has occurred, and in the BaseBinaryStar class we need to react to that and resolve it, and we do that by calling BaseBinaryStar::ResolveSupernova() – at least that was my reasoning behind implementing it that way.  I may have implemented it incorrectly – or perhaps not quite correctly – but that doesn’t change the concept behind it – we should, in my opinion, try to encapsulate functionality in high-level functions that capture the essence, or overall goal, of what we’re trying to achieve (in this case resolve a supernova event in one of the constituent stars), then those functions can take care of the details (which might include calling lower-level, more detailed, more specifically named, functions) – but the high-level function with the overall goal is where we go when we want to look at the code that resolves supernova events (and is the only function that needs to know how it is done).

So, back to the point.  Having BaseStar::ResolveSupernova() and BaseBinaryStar::ResolveSupernova() is, I think, perfectly natural.  I would actually be surprised if both classes didn’t implement functions with those names.  If I read the SSE code and saw BaseStar::ResolveSupernove() and was prompted to wonder how the BSE code resolved a supernova event, I would go looking for a function in the BSE code named “ResolveSupernova” – not finding it would confuse me more than finding it.
(I think the same arguments apply to variable names in different class – I don’t see a problem having, say, m_Mass in the BaseStar class and m_Mass in the BaseBinaryStar class (if m_Mass for a binary is a well-defined value), but this issue is specifically about function names).

Anyway, I’ve prattled on enough – so much that I think I’ve forgotten a lot of what I intended to write 😊

To be clear, what I’m trying to defend here is the OO paradigm – not my implementation of it or my choice of function and variable names.  I have no sentimental attachment to any of the code I’ve written (except maybe the functionality to change the content of the output files at runtime 😊 – that was interesting to write)…

In the end, if any function names are confusing people more than they are enlightening them, then they should be changed.  My lack of sentimental attachment extends to function names so, apart from the OO and code-clarity implications I’ve detailed above, I have no problem with changing any of them to something more appropriate.

**Comment by ilyamandel** [comment]
I generally agree with most of what Jeff wrote above.  My objection is certainly not with the OOP paradigm.  I simply wish to clarify function names.  Here, I did not find them sufficiently clear.  I would not have this problem if the individual stars' ResolveSupernova() functions were called from BaseBinaryStar::ResolveSupernova() -- but they are not.  So the process of resolving stellar supernovae is, in fact, split across multiple functions in BaseBinaryStar, which is why calling one of them "ResolveSupernova" is confusing to this particular developer.

**Comment by jeffriley** [comment]
> So the process of resolving stellar supernovae is, in fact, split across multiple functions in BaseBinaryStar, which is why calling one of them "ResolveSupernova" is confusing to this particular developer.

But resolving stellar supernovae is up to the BaseStar class, which it does.  Then the binary star has to deal with it. Maybe the problem here is (my) poor terminology stemming from my limited understanding of the process.

My naive understanding is that one of the constituent stars explodes, and it deals with that (in BaseStar and its derived classes), then the binary has to deal with it.  The binary dealing with it follows the individual star dealing with it doesn't it?  Both functions are called ResolveSupernova because that's what they do (my understanding) - it's just that the single star deals with it when it happens (because it has to), and the binary star deals with it when it knows about it (after it happens), but both resolve the event (in their context).

Having said that, it's obviously causing confusion, so I'll stop opining and let you get on with changing the name.

**Comment by ilyamandel** [comment]
On the contrary, I think I should stop distracting you and let you get on with more important things. ;-)

**Comment by ilyamandel** [comment]
Whether or not I am convinced by @jeffriley , this belongs in the Won't Fix category -- and since I raised this, I am closing it  immediately, without waiting for a month. :)
