### ISSUE TITLE
Update coalescence time calculation

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#352]
**Is your feature request related to a problem? Please describe.**
Not a problem, just an improvement. Peters (1964) equations can be wrong by factors of ~30-40%, new equation by Zwick et al. 2020 accounts for this.

**Describe the solution you'd like**
Change CalculateTimeToCoalescence to use new Zwick et al. 2020 equation 41 for coalescence time. This will both avoid numerical integration (added speed) and account for PN corrections (added accuracy). I posted code that should solve the issue in the Slack group.

**Describe alternatives you've considered**
You could also just leave the original Peters equations.

**Additional context**
None

**Comment by ilyamandel** [comment]
Very nice, @TomWagg !   If I understand correctly (I only quickly glanced at Zwick+), their first correction should only impact eccentric binaries, increasing their merger timescales.  The second correction will be irrelevant for typical stellar-mass binary mergers through isolated binary evolution.  I'd like to check the paper more closely before including the code; will aim to do so ASAP, but probably not in the next few days.

**Comment by ilyamandel** [comment]
@TomWagg -- I looked into this.  I am skeptical about the Zwick result, so am closing this issue until I get a clarification from Zwick.  I've forwarded my query to you, but for the public record, I'm also copying it here:

===

Dear Lorenz,

I was interested by your recent paper, https://ui.adsabs.harvard.edu/abs/2020MNRAS.495.2321Z/abstract , which provides a corrected calculation of the gravitational-wave merger timescale without the need for integration (cf. Peters, 1964, eq. 5.14 — by the way, I think your comparison to “the Peters timescale” is slightly misleading, because Peters quite clearly intended for this expression to be used to estimate the coalescence timescale, except for special cases e<<1 or (1-e)<<1, while you use a different timescale for comparison).

However, while I find that your expression (eq. 41 of your paper) is a good match to the integral (5.14) of Peters at high eccentricity, I find a significant discrepancy at low eccentricities of ~0.1.  Moreover, I see that, for fixed masses and initial semi-major axis (two 30 Msun components and a0=40 Rsun in my example), your expression yields non-monotonic timescales as a function of eccentricity, which I find very surprising indeed.  Could you perhaps cast some light on this?

[PastedGraphic-1.pdf](https://github.com/TeamCOMPAS/COMPAS/files/5177471/PastedGraphic-1.pdf)

Best wishes,
Ilya
