### ISSUE TITLE
Grids-Proposal Discussion

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#412]
**Discussion of the new branch `grids-proposal` that Jeff put together to expand grid functionality.**

[GridsProposal.pdf](https://github.com/TeamCOMPAS/COMPAS/files/5442633/GridsProposal.pdf)

**Comment by reinhold-willcox** [comment]
My feedback: 

- Overall, this a big improvement and very helpful for my project. Nice job! 
     
- This has been mentioned before, but moving forward we need to establish COMPAS defaults, which are explicit and agreed upon. I think a lot of progress has been made on this front for the methods paper, but if we continue using pythonSubmit, the default values there should also be COMPAS defaults (so the user can at least see them).    
     
- If we can reset a parameter using just the OPTIONS->OptionGetter() function, is there a way to determine (from the output) that an injected parameter value was used in place of a calculated value?    
     
- Regarding ranged inputs, do we have the option for logarithmic ranges? Is it even a good idea to implement this? Alternatively, we could configure the pythonSubmit to do this (since python already has very extensive ranging options), and then submit only singular values into the grid file? Personally, I would prefer the second option, so that there is a one-to-one correspondence between lines in a grid file, including the identifying seed.
     
- `number-of-stars  single/binary`  - I propose we change this to "number-of-star-systems" or "number-of-systems" for clarity.

- I agree with removing 'BSE_' prefixes, they can be considered redundant.

- I mentioned this on Slack, but we need to clean up how we do sampling when some systems are rejected initially. Tagging @FloorBroekgaarden and @lokiysh to get their thoughts.

**Comment by jeffriley** [comment]
> If we can reset a parameter using just the OPTIONS->OptionGetter() function, is there a way to determine (from the output) that an injected parameter value was used in place of a calculated value?

You can print the value of the option in the log file (whichever log file you want it in)


> Regarding ranged inputs, do we have the option for logarithmic ranges?

Sure - we just have to settle on how we want to denote it (i.e. what the user would type) and then write code to parse that and set the values appropriately - none of this comes to us from a library, so we have to write the code ourselves (but the upside of that is we're free to do it however we want).


> Personally, I would prefer the second option, so that there is a one-to-one correspondence between lines in a grid file, including the identifying seed.

You don't have to use ranges or sets in a grid file if you don't want to, so you can still have a 1:1 correspondence - so you could set pythonSubmit up to do it that way.  As long as whatever we do doesn't force users to use pythonSubmit if they prefer to run COMPAS from the commandline - I'm all for not constraining users where we don't have to.


> number-of-stars single/binary - I propose we change this to "number-of-star-systems" or "number-of-systems" for clarity.

I'm easy.  I chose against "systems" because I figured a single star isn't a system, but a binary star could still be called a star - but I really have no preference other than whatever we use doesn't obfuscate the use of the option.

**Comment by reinhold-willcox** [comment]
> > Regarding ranged inputs, do we have the option for logarithmic ranges?
> 
> Sure - we just have to settle on how we want to denote it (i.e. what the user would type) and then write code to parse that and set the values appropriately - none of this comes to us from a library, so we have to write the code ourselves (but the upside of that is we're free to do it however we want).
> 
> > Personally, I would prefer the second option, so that there is a one-to-one correspondence between lines in a grid file, including the identifying seed.
> 
> You don't have to use ranges or sets in a grid file if you don't want to, so you can still have a 1:1 correspondence - so you could set pythonSubmit up to do it that way. As long as whatever we do doesn't force users to use pythonSubmit if they prefer to run COMPAS from the commandline - I'm all for not constraining users where we don't have to.
>

That's a fair point, I'm happy with the current implementation then. At some point I'll work on setting up the pythonSubmit to do ranges as well.
 
> > number-of-stars single/binary - I propose we change this to "number-of-star-systems" or "number-of-systems" for clarity.
> 
> I'm easy. I chose against "systems" because I figured a single star isn't a system, but a binary star could still be called a star - but I really have no preference other than whatever we use doesn't obfuscate the use of the option.

I would actually argue the opposite - a single star is a system (e.g the Solar System, or the Dagobah system), but binary star is really shortened from binary star system.

**Comment by jeffriley** [comment]
> a single star is a system (e.g the Solar System, or the Dagobah system)

Hah!  I would argue that a single star is *in* a system - and that COMPAS doesn't evolve planets or moons!  However, I'm happy with 'number-of-systems' :-)

**Comment by jeffriley** [comment]
From Slack:

>One thing I wanted to mention here though, which you comment on, is that we need to think more closely about the random sampling. I believe @Floor Broekgaarden and @Loki maybe have thought a lot about how the sampling distributions are affected if we throw out some systems at birth. Due to possible correlations in the initial distributions, if we are not careful about how we resample those parameters, we may skew the intended sampling distributions.

My thoughts on this are that we should have very basic sampling in the COMPAS C++ code for the initial conditions, so that users can specify some of the initial conditions and have the ones they leave out sampled.  The problem Reinhold alludes to (I think) is that if a user used (e.g.) Stroopwafel to sample (say) the initial mass of the primary using a particular distribution (that is different from the IMF in the COMPAS C++ code), then if:

(a) COMPAS rejects a binary (from a grid file), or
(b) the user leaves out the primary initial mass in some grid file lines

the value sampled in the COMPAS C++ code would affect the distribution of primary masses.  I think Reinhold is absolutely right.

I think the solution to (a) might just be to reject without replacement.
The solution to (b) is either "don't do that" (or live with it if you do), or the same as for (a) - reject the binary without replacement.

We could, if we want to be a little more sophisticated, investigate ways that users could provide COMPAS with either libraries or code to sample from specific distributions (this harks back to something Ilya talked about when I first started refactoring the code).  I'm not sure we need to get that sophisticated - in the end, if the user wants to use a specific distribution, then specify all the initial conditions in the grid file - don't leave any out (so the COMPAS C++ code doesn't need to sample).  And in the case of rejected binaries - either check the conditions in Stroopwafel (so no binaries that would be rejected make it to the COMPAS C++ code), or provide sufficient binaries so that if some are rejected without replacement you still have enough for your study.

**Comment by ilyamandel** [comment]
Addressed by PR #423, closing.
