### ISSUE TITLE
Nuclear timescale calculation makes assumptions about core mass

### ISSUE THREAD

**Issue by TomWagg** [TeamCOMPAS/COMPAS#430]
**Describe the bug**
Whilst plotting the nuclear timescale with Selma we noticed that it seemed off by a factor of ~3-5 from what it should be for high mass stars. The timescale doesn't seem to be used in any meaningful way except printing so only problem would be when people are using this for other things. The equation used by COMPAS is assuming that core mass makes up a certain fraction of the total mass, so it works for solar mass stars but once you get to higher mass stars things get iffy.

**Label the issue**
`urgency_low`,`severity_moderate`

**To Fix**
See [BaseStar::CalculateNuclearTimescale_Static](https://github.com/TeamCOMPAS/COMPAS/blob/production/src/BaseStar.cpp#L2230). This uses the last expression of Kalogera & Webbink 1996 Eq.3, but if you look at this equation in the text you see you should really be using the core mass expression, not using the second expression
<img width="578" alt="image" src="https://user-images.githubusercontent.com/21990332/98278169-374f4800-1f66-11eb-9b5e-d8f931e7105f.png">

**Comment by SimonStevenson** [comment]
I'm shocked that we even have this. I suggest simply removing it, since time-scales should be self consistently calculated from the stellar models (currently SSE)

**Comment by TomWagg** [comment]
Okay gotcha, in that case would CalculateDynamicalTimescale also be up for the chop?

**Comment by SimonStevenson** [comment]
We could certainly make your fix, just seems odd that we have this if we don't use it. I think we may actually use the dynamical timescale for something (we can check); if so we better not remove that

**Comment by reinhold-willcox** [comment]
I think the dynamical timescale is just used as a lower bound. We also have a hardcoded minimum timescale, so I believe the larger of these two at any given timestep is taken as the lower bound.

**Comment by ilyamandel** [comment]
This is meant to be a crude estimate, for potential use only when crude estimates are useful (e.g., when deciding on appropriate time step sizes).  We can remove it, but I don't see much harm.  I don't think we can make the fix @TomWagg  suggests, though: there's no core mass as such for MS stars.  A more relevant simple fix to be to change the energy efficiency for more evolved stars -- the helium mass deficit is lower than the hydrogen much deficit. :)

In any case, I don't think this is a particular issue provided this is only viewed as a crude estimate...  But since we don't use it except during CEE printing (where it's typically very incorrect because these are evolved stars that are fusing He, not because the core mass fraction is wrong), let's just remove it.

The dynamical timescale estimate is correct as far as I can tell, so no reason to change that.

**Comment by ilyamandel** [comment]
As a reminder, the proposed solution is to remove BaseStar::CalculateNuclearTimescale_Static and remove it from output.

**Comment by ilyamandel** [comment]
Finally addressed in #1109
