### ISSUE TITLE
Parameter --kick-magnitude not working

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#535]
**Describe the bug**
The input parameter `--kick-magnitude` appears to not be working, although both `--kick-magnitude-1` and `--kick-magnitude-2` work as advertised. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**

Run `COMPAS --kick-magnitude 666 -n 100`. In the output, none of the drawn kicks are set to the correct value. The following python script may help.

```
import h5py as h5   
Data  = h5.File(COMPAS_Output.h5, 'r')
print(Data['BSE_Supernovae']['Drawn_Kick_Magnitude(SN)'][()])
```

**Expected behavior**
As with other parameters which may have a -1 or -2 extension for the primary/secondary star, if the extension is left off, the parameter should be applied to both primary and secondary. 

 - COMPAS . v02.18.07

**Comment by jeffriley** [comment]
This is more a documentation issue rather than functionality.

Option --kick-magnitude is for a single star (SSE mode) - it was not meant to set the kick magnitude for each of the stars in a binary (in BSE mode).  To do that (set both stars in BSE mode), the user needs to specify both --kick-magnitude-1 and --kick-magnitude-2 (This is how all similar options are coded - e.g. --initial-mass, --initial-mass-1, --initial-mass-2, --rotational-frequency, --rotational-frequency-1, --rotational-frequency-2, etc.).

We could make the base option name (in this case, --kick-magnitude) set both --kick-magnitude-1 and --kick-magnitude-2 if used in BSE mode, but it might get confusing (especially if the user also specified --kick-magnitude-1 and/or --kick-magnitude-2).

For now, I think it is better just to make the documentation clear.  I suggest changing the documentation for --kick-magnitude and its variants (and any similar options that haven't been properly documented) to be similar to the documentation for --rotational-frequency (where SSE and BSE are explicitly noted):

--rotational-frequency
  Initial rotational frequency for the star for SSE (Hz) (default = 0.000000)
--rotational-frequency-1
  Initial rotational frequency for the primary star for BSE (Hz) (default = 0.000000)
--rotational-frequency-2
  Initial rotational frequency for the secondary star for BSE (Hz) (default = 0.000000)

**Comment by reinhold-willcox** [comment]
Closing this issue. The problem was in my misunderstanding the functionality of the parameter, the code is working fine.
