### ISSUE TITLE
Post-processing testing

### ISSUE THREAD

**Issue by ilyamandel** [TeamCOMPAS/COMPAS#558]
Since many of us do not usually run jupyter notebooks but may from time to time inadvertently impact them with other code changes, it would be great to have a simple test script that would:
1. Compile COMPAS
2. Do a small run of COMPAS
3. Run post-processing via Jupyter notebooks 
4. Create a log of any issues encountered

This wouldn't check for correctness, merely execution failures.  A future option would be to create a couple of simple plots that could be used for visual regression testing.

**Comment by reinhold-willcox** [comment]
Adding to this issue, some very low-priority TODOs related to the post-processing scripts. I am happy to take them on at a later date.

- Versioning jupyter notebook files (.ipynb) is a pain because of all the excess metadata and the annoying format of the source code. Jupytext converts notebooks into python files, which are still readable as the original notebook, and are much easier to version. We should save all notebooks as .py files for the repo, and then have any ipynb files (and probably the related html files) generated with some script automatically. 
- The COMPAS path in ClassCOMPAS.COMPASData should be more flexible. In particular, if I submit a full path with data file, the script should recognize that and internally split into directory path + file. 
- Some of the hyperlinks in jupynbs point towards files in parent directories. If the notebook is launched from the child directory, the link will not work. We should probably rethink the notebook directory structure to make this more consistent.

**Comment by reinhold-willcox** [comment]
The linked PR does not solve the main issue listed here, but does solve some of the the follow up points I raised in the comment above.

That said, the updated notebooks should be easier to set up versioning for. This is something I have discussed with Avi, and should be fairly straightforward to implement.
