### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#560]
**Is your feature request related to a problem? Please describe.**

Related to Issue #558, we should incorporate continuous integration (CI) tests into Github, as a simple way to automatically test / compile parts of the repo that may have been inadvertently affected by other changes. 

The CI should include:
- tests on the post-processing pipeline, including the jupyter notebooks. 
- compilation of the documentation *.tex files, and inclusion of the compiled .pdf in the repo

**Comment by reinhold-willcox** [comment]
Also related to the discussion in #543

**Comment by reinhold-willcox** [comment]
Adding to this: creation of a new git tag for every time we change the version number.

**Comment by jeffriley** [comment]
@reinhold-willcox Can we easily check whether the C++ compile and/or the LaTeX compile is actually necessary?  I just opened a PR for a small change to one of the post-processing python files - no C++ file or LaTeX file was modified, but the checks for the C++ and LaTeX builds were run.  The github runners aren't exactly the speediest systems and the COMPAS build takes a few minutes.  It's not a huge issue, especially since the builds are happening in the cloud somewhere so don't really impact us (other than having to wait a few minutes for them to complete), but if we can easily add a simple git-diff or something to check whether any C++ or LaTeX files were actually changed maybe we could look at that.

**Comment by reinhold-willcox** [comment]
Yes, a git diff should be straightforward. ~I'll add an issue for it~ (edit: I'll just leave this issue open for now), but not 100% sure when I'll have time to add it in.

**Comment by reinhold-willcox** [comment]
TODO at a later date:

- If there were changes to the source code, setup a CI to rerun the test runs (maybe in a Docker container?)
- If the version is changed in changelog.txt, create a new git tag with the appropriate version name. Then if we want to checkout a specific version, it's just a `git checkout v20.02.XX`, instead of trying to dig through the history of logs.

**Comment by reinhold-willcox** [comment]
Adding to this:
- Add a CI to check that the online-docs compile
- Add a CI to check that the jupyter notebooks compile

**Comment by reinhold-willcox** [comment]
#730 solves the online-docs autocompilation test

Add to the TODOs: remove the latex-ci files now that we don't keep latex documentation
