### ISSUE TITLE
Bloated SystemParameters output

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#613]
**Is your feature request related to a problem? Please describe.**
The BSE_System_Parameters output seems a bit bloated in its current state, with many parameters that are probably better suited for other output files. Examples include anything relating to initial distribution hyperparameters (e.g `Metallicity_Dstrbtn`, `Metallicity_Dstrbtn_Max`, `Metallicity_Dstrbtn_Min`) or other constants across a given run which really belong in Run_Details. Also, there are `Semi-Major_Axis` and `SemiMajorAxis@ZAMS` which will always be the same (unless something is broken, but then both should only be printed if troubleshooting). 

Interestingly, the SemiMajorAxis parameter in BSE_Supernova is in units of Rsol, whereas in BSE_System_Parameters it is in AU. These should be set to the same units to avoid needless confusion.

There are also all of the parameters related to SN kicks. Many of these are repeated in the BSE_Supernova output, and I can't think of a reason why we would care about the value of those parameters for systems which do not undergo SN. 

**Describe the solution you'd like**
General clean-up of the SystemParameters output, both to reduce hdf5 file size and to improve clarity for users.

**Comment by jeffriley** [comment]
@reinhold-willcox I think what you're seeing is a result of adding the option values to the system parameters file - that was done so that the different values of options on different grid file lines would be saved with the system parameters.  This was added in v02.19.00.  There is a new option: "--add-options-to-sysparms" which defaults to "GRID".  If you specify "NEVER", you'll find the bloat in the system parameters file goes away.

See the documentation for program option "--add-options-to-sysparms" for option values..

**Comment by reinhold-willcox** [comment]
Closing this issue in light of Jeff's comments, and because I had originally asked for this functionality.....
