### ISSUE TITLE
move all sampling of initial binaries outside of COMPAS & to `Grid.txt`

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#71]
All functions that are currently in `pythonSubmit.py` that do the sampling, e.g. 

```
    initial_mass_function = 'KROUPA'
    initial_mass_min = 5.0          # Use 1.0 for LRNe, 5.0 for DCOs  [Msol]
    initial_mass_max = 150.0        # Stellar tracks extrapolated above 50 Msol (Hurley+2000) [Msol]

    initial_mass_power = 0.0

    semi_major_axis_distribution = 'FLATINLOG'
    semi_major_axis_min = 0.01  #  [AU]
    semi_major_axis_max = 1000.0  #  [AU]

    spin_distribution = 'ZERO'
    spin_assumption = 'BOTHALIGNED'
    spin_mag_min = 0.0
    spin_mag_max = 1.0

    mass_ratio_distribution = 'FLAT'
    mass_ratio_min = 0.0
    mass_ratio_max = 1.0

    minimum_secondary_mass = 0.1 # Brown dwarf limit  [Msol]

    eccentricity_distribution = 'ZERO'
    eccentricity_min = 0.0
    eccentricity_max = 1.0

```

could be moved to a pre-processing script in python that does all the sampling (e.g. from the IMF) in Python, and then adds them to `Grid.txt`. This Grid.txt is then read in by the main COMPAS function. 

This is the most consistent way of sampling that is also very helpful for a statistical framework (e.g. stroopwafel / dart_board / UQ sampling)

**Comment by ilyamandel** [comment]
If I understand correctly, this is already handled with @lokiysh 's code.  That said, I suggest that we keep the basic sampler in COMPAS for now so it can continue to be run without that external tool.  So I do not think there's anything to be done on this issue.

@lokiysh , @FloorBroekgaarden , @SimonStevenson , @reinhold-willcox -- please comment in the next week if I am mistaken, otherwise, I will close this.

**Comment by ilyamandel** [comment]
Closing based on the above and Stephen's comments.  If there are specific bugs/features, please add them as new issues.
