### ISSUE TITLE
NaN radius

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#711]
**Describe the bug**
(copied from slack) The attached system goes through 2 MT episodes, the second of which is a merger (though not very clearly recorded). The first MT is the weird one though. It's stable, very conservative MT, from CHeB to CHeB. But after the first MT, the radius of the companion becomes a NaN. Then, by the time of the second MT, the secondary radius is back to a normal value! Sometimes there will be NaN's in the event of a merger (as is the case for the second MT, where the postMT semi-major axis is a NaN), but it doesn't make sense why the radius would be a NaN when there is no merger, then convert back.

![image](https://user-images.githubusercontent.com/33348824/143191833-7a022128-126b-4e7c-bff5-1c8909dc0fdf.png)

**Label the issue**
Please label the 'severity' and 'urgency' of this issue. You can choose:

`urgency_moderate` - This is a moderately urgent issue
`severity_moderate` - This is a moderately severe bug

**To Reproduce**
The output and detailed output are included below (it's just a single system, so the files aren't too big), which also give you the input parameters if you want to rerun. 
*Note:* github is annoying about file extensions, so these have both been "converted" to .txt files, just mv them back to h5 and they'll run.

 - COMPAS v02.25.9
[COMPAS_Output.h5.txt](https://github.com/TeamCOMPAS/COMPAS/files/7593429/COMPAS_Output.h5.txt)
[BSE_Detailed_Output_0.h5.txt](https://github.com/TeamCOMPAS/COMPAS/files/7593432/BSE_Detailed_Output_0.h5.txt)

**Comment by jeffriley** [comment]
@reinhold-willcox Did you mean v02.25.00, or is that a typo?

There aren't that many places in the code that a star's radius is modified - if you are able to reproduce this consistently then it shouldn't be hard to figure out where the radius is becoming NaN - once you know where you might get a clue as to why (divide by zero, or similar).  Knowing where the problem occurs, and an indication of why, it shouldn't be too difficult to track down the root cause.

**Comment by reinhold-willcox** [comment]
@jeffriley typo, thanks for catching, fixed now

**Comment by jeffriley** [comment]
Ok, let me know if you need help with debugging.
