### ISSUE TITLE
Output when the star hits a user-specified fraction of the Roche lobe

### ISSUE THREAD

**Issue by IsobelMarguarethe** [TeamCOMPAS/COMPAS#746]
I don't think this is a thing that is currently output, and it would be useful if it was. :)

**Comment by reinhold-willcox** [comment]
It should be calculable from the available parameters. Are you looking at BSE_RLOF?

**Comment by ilyamandel** [comment]
@IsobelMarguarethe -- as @reinhold-willcox writes, you can get this fraction already.  You can find the list of available quantities you can write to log files here:

https://compas.readthedocs.io/en/latest/pages/User%20guide/COMPAS%20output/standard-logfiles-record-specification-stellar.html

https://compas.readthedocs.io/en/latest/pages/User%20guide/COMPAS%20output/standard-logfiles-record-specification-binary.html

The thing you are asking for you can already get as RADIUS / ROCHE_LOBE_RADIUS.  

But what I think you actually wanted was something different: an ability to output a line when a star fills a given fraction (say, 80%) of the RL.

**Comment by IsobelMarguarethe** [comment]
You're right - I misremembered. I've changed the title of the issue to reflect the change we actually want

**Comment by reinhold-willcox** [comment]
This is doable, but it depends somewhat on what output you'd like. If you're thinking about this for a single system, the detailed output will have the information you're looking for. If you're doing this for a population, you'll have to decide what output file makes the most sense. BSE_RLOF might be the most sensible, although because this would be pre- mass transfer, there would be some values that don't make sense there. What is your use case?

**Comment by IsobelMarguarethe** [comment]
It's for a population, where we'd like to be able to observe the properties of systems when they are 80% Roche Lobe filling. Could a custom output file be created? If a system gets to 80% RL filling it's likely to get to 100% RL filling at some point, so BSE_RLOF might still be an ok place to put them.

**Comment by reinhold-willcox** [comment]
A custom output file is tricky, @jeffriley will be able to answer you better.

A quicker, hackier alternative, depending on how many and which parameters you need, would be to std::cout your parameters of interest when you reach the threshold, run COMPAS with the output piped to a file, and remove all the excess lines you don't need.

**Comment by jeffriley** [comment]
All the infrastructure is in place to create a new output file - it's a little tedious, but not difficult.

If this is a useful thing to do, is it something we want to be available to other researchers as a feature of COMPAS, or is it a one-off thing?  I think the former, and if that is so we have a couple of options: a new output file, or use the existing BSE_RLOF file.

If we create a new output file then we're free to do whatever we like with it.

If we use the existing RLOF file then we'd need a new column in the file that indicates the entry type - 80% full or overflow.  That's not difficult, and easy to use as a filter for post-processing.  I suggest the trigger for writing an entry to the BSE_RLOF file be a commandline parameter (a program option), and maybe we should allow users to input multiple triggers so that entries are written for different filling %s, with "overflow" being hard-coded (so an entry would always be written for overflow).  So the then "type" column would just show the % full for that entry (with, say, 100 for overflow) - again, easy to use as a filter for post-processing.

**Comment by IsobelMarguarethe** [comment]
Jeff's final suggestion sounds like a good way forward.

**Comment by jeffriley** [comment]
@IsobelMarguarethe Can this be closed now?

**Comment by IsobelMarguarethe** [comment]
Yep sorry I forgot to do this!
