### ISSUE TITLE
MergerAtZams missing equilibrated binaries which still RLOF

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#782]
**Describe the bug**
The MergerAtZams flag is great for determining if two stars were initially positioned too closely. However, some systems do not merge at ZAMS, but very shortly after (1 timestep, <.02 Myr).

Looking closely at these systems, they all undergo RLOF and equilibrate at birth. These equal mass binaries are then checked for whether their radii overlap (2R < a), but not whether they overflow the RL _after_ the equilibration. The ones which overlap are correctly flagged as a merger at zams, and the ones which do not overlap or RLOF (a second time) evolve as CHE binaries as expected. But the subset which do not overlap but _do_ RLOF should be considered as mergers at birth. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
Steps to reproduce are a bit involved. You need to add the initial radii and simulation time to the `BSE_System_Parameters` output, so create a logfile_defs.txt with the following:

logfile_defs.txt :
```
bse_sysparms_rec += {    
    STAR_1_PROPERTY::RZAMS,    
    STAR_2_PROPERTY::RZAMS,    
    BINARY_PROPERTY::TIME,    
}    
```

Add any of the following seeds to a gridfile:
 ```
1649389693 1649389695 1649389703 1649389722 1649389752 1649389771 1649389786 1649389843 1649389860 1649389868 164938 9875 1649389894 1649389901 1649389999 1649390043 1649390060 1649390063 1649390083 1649390194 1649390240 1649390323 16 49390335 1649390336 1649390342 1649390414 1649390423 1649390477 1649390506 1649390510 1649390512 1649390560 164939058 1 1649390584 1649390594 1649390601 1649390623 1649390624 1649390644  
```

And run with the following flags to allow for touching and rlow at ZAMS to avoid having these systems flagged as errors and thrown out.

`COMPAS --grid grid.txt --logfile-def logfile_defs.txt --semi-major-axis-max 10 --allow-touching --allow-rlof`

Then you can use the following script to see the error (or write your own, as you like).
```
SPs = h5.File('COMPAS_Output/COMPAS_Output.h5', 'r')['BSE_System_Parameters']

isEquil = SPs['Equilibrated_At_Birth'][()] == 1
RZams = SPs['Radius@ZAMS(1)'][()]
AZams = SPs['SemiMajorAxis@ZAMS'][()] * 215 # Rsol
Time = SPs['Time'][()]

RL_a = 0.49/(0.6 + np.log(2)) # 0.379: RL/a for q=1 

for rZams, aZams, time, equil in zip(RZams, AZams, Time, isEquil):
    RLZams = RL_a*aZams
    print("equil={}, t={:.5f}   rZams={:.2f},    rRL={:.2f},    aZams/2={:.2f},  ".format(equil, time, rZams, RLZams, aZams/2)) 
```

The output shows that all systems here are equilibrated (so we know r1 = r2), that the binary completes its evolution at a time t>0, and that the zams radius is greater than the RL radius but smaller than half the separation. These systems should all be mergers at ZAMS. 

**Versioning (please complete the following information):**
 - COMPAS v02.27.07

**Comment by jeffriley** [comment]
Does --allow-rlof-at-birth make a difference here (default is TRUE - what happens if it is FALSE)?

**Comment by jeffriley** [comment]
What happens if you set --allow-rlof-at-birth false?

**Comment by jeffriley** [comment]
> But the subset which do not overlap but do RLOF should be considered as mergers at birth.

Aren't these the binaries Pablo is talking about in https://arxiv.org/abs/1601.03718 ?

**Comment by reinhold-willcox** [comment]
If we were more careful about how we calculate the equilibration, we might reproduce some of their systems which transfer mass back and forth until the mass ratio levels out (with possibly some mass loss due to non-conservative MT), leading to an ultimately detached but very close CHE binary. But in our case, these are merging systems, we're just not calculating the merger at the right time.

**Comment by jeffriley** [comment]
But they don't merge until they overflow L2, and I think by that time they are touching - or maybe I'm misremembering.  I'll go back and read the paper.

**Comment by reinhold-willcox** [comment]
We could modify the equilibration prescription to allow for more survivors, but that's probably a longer term feature addition. For this I think we just need to make sure we flag these correctly before the evolution starts.

**Comment by jeffriley** [comment]
> However, some systems do not merge at ZAMS, but very shortly after (1 timestep, <.02 Myr).

So the binaries in question are not being picked up and flagged by this code in BaseBinaryStar::Evolve():

    if (HasStarsTouching()) {                                                                                                               // check if stars are touching
        m_Flags.stellarMerger        = true;
        m_Flags.stellarMergerAtBirth = true;
        evolutionStatus              = EVOLUTION_STATUS::STELLAR_MERGER_AT_BIRTH;                                                           // binary components are touching - merger at birth
    }

That code is executed at the start of the first timestep - so if that's not catching them they are merging after (or during) the first timestep?

**Comment by jeffriley** [comment]
I am not convinced - but am willing to be - that we need to do anything here.  If the binary isn't touching at the start of evolution, and so marked as "Merger_At_Birth", and we've indicated we want to allow RLOF at birth, why don't we just let it do its thing and merge later if it's going to?  Plenty of other binaries merge after birth and we don't take them out - why wouldn't taking out the ones that have a star, or stars, that undergo RLOF at birth but merge later bias our results?  We said we wanted to allow RLOF at birth - why would we consider binaries that have a star, or stars, that undergo RLOF at birth as mergers at birth?

Edit: if a binary that does not have a star, or stars, undergoing RLOF at birth merges in the first few timesteps, why would we not call that a merger at birth?  If the real concern is that some binaries merge very soon after birth - so soon that we really should consider them as mergers at birth - why would we not just consider all stellar mergers that occur within some arbitrary time (not timesteps) after birth as mergers at birth (rather than just those that were undergoing RLOF at birth)?

**Comment by ilyamandel** [comment]
1. RLOF per se does not mean merger: the whole point of --allow-rlof is to allow over-contact binaries.
2. Systems that "touch" are really in L2 overflow -- there's no saving them, they will merge.  --allow-touching is just there to force these systems to be recorded.  I think what @reinhold-willcox is arguing is that systems in this configuration should be recorded as mergers on the first time step rather than the second one.  Fine by me, but that's the only change which seems necessary.

**Comment by jeffriley** [comment]
> I think what @reinhold-willcox is arguing is that systems in this configuration should be recorded as mergers on the first time step rather than the second one. 

If the stars are touching at the start of evolution they are recorded as mergers at birth.  The check there is for a <= (R1 + R2).  That's at the start of the first timestep.

I don't think we should use timesteps here as the unit of time - what if the user used a timestep multiplier of (say) 1000?  Or 1000000?  That was my point about using some arbitrary in my earlier post.

I agree we could check for actual merger (touching/L2 overflow) within some arbitrary time since birth, and call that a merger at birth, but I don't think the check should be for RLOF.  And the cehck would then be more general, in that it would catch any system that was touching withing that timeframe, not just those that were in RLOF at birth (though they would probably be the ones that ended up touching so soon).

Edit:
> what if the user used a timestep multiplier of ....

I suppose if that's the timestep they're interested in, maybe we could use timestep - but I don't think I like it ;-)

And... it would be difficult to calculate an intra-timestep time anyway.  Ok, I give up on the time vs timestep thing - but I still don't think I like it.

**Comment by jeffriley** [comment]
Also, as @ilyamandel noted, --allow-touching-at-birth (and the "Merger_At_Birth" flag) was implemented to allow systems touching at birth to be included in the stats, but identifiable as systems that didn't evolve as binaries past birth.  If what is really required here is that systems that merge in the first timestep (or second, or third...) also be identified as systems that didn't evolve as binaries, that can be done in post-processing - and there the user has the flexibility to decide how many timesteps after birth they'll give the system to merge.

**Comment by reinhold-willcox** [comment]
Apologies, I may have been unclear (and somewhat misinformed) in my earlier responses. 

My concern is with the implementation of '--allow-rlof', not '--allow-touching'. Currently, '--allow-rlof-at-birth' only checks if there is RLOF at birth. That matches what would be expected given the option name, but if this is intended to allow for over-contact binaries, we should be including a check for this option in all timesteps. Right now, for a given binary that is run with '--allow-rlof' and equilibrates at birth, which is then a detached binary but with both components RLOFing, it is told to survive and continue evolving as an over-contact binary. But after the first timestep, a negligible amount of time has passed and the virtually identical binary is identified as having both MS components overflow their RLs, but this is now flagged as a CE and merger event.

My point is that if we are allowing for over-contact binaries, we should do this consistently throughout the evolution and not just at the first timestep. This is different to my earlier point so please ignore that. For now, I think I can simply turn this flag off and achieve the functionality I need. Edit: yes, turning off the flag works.

**Comment by jeffriley** [comment]
> But after the first timestep, a negligible amount of time has passed and the virtually identical binary is identified as having both MS components overflow their RLs, but this is now flagged as a CE and merger event.

Isn't that what we'd expect to happen if the stars aren't spinning fast enough to be chemically homogeneous stars?  I'm not sure what else we would do - do you have an alternative in mind?

If we allow for the possibility of over-contact binaries (so use --allow-rlof-at-birth) we wouldn't expect a clean bifurcation of binaries that have stars rotating fast enough to be CH stars, and binaries that have stars that won't merge for a long time, would we?  Wouldn't we expect that because of the range of component masses at birth some binaries might have stars that are on the cusp of spinning fast enough to be CH, but not quite - and those binaries will likely merge soon after birth?  Turning --allow-rlof-at-birth off is one way of ensuring you don't get those binaries merging early, but it also means you don't get over-contact binaries.  Why not just leave --allow-rlof-at-birth on and filter out the binaries that merge in the first couple of timesteps in post-processing if you don't like them?  (Though I don't know why you would - I don't think I really understand the problem.  They're not really mergers at birth - if they spin fast enough to evolve as CHE binaries they might have long and meaningful lives, but if not they merge early (and over a range of times, but not at birth)).

We check at every timestep (on the MS) whether CH stars have spun down below the CH threshold, and if they have they switch to MS stars - and then maybe they merge because they are so close together and their radius is no longer clamped (and that might be early in the evolution of the binary).

**Comment by reinhold-willcox** [comment]
If the condition for an over-contact binary to survive for some amount of time is set by the rotation, I agree with you that we should see some sort of continuity between over-contact / CHE stars and merging stars based on the spin down. That's probably a good idea for a future feature, whenever we implement stellar rotation. 

But here we're saying that binaries in RLOF at precisely ZAMS should survive, but immediately after that they should merge, which is not physical or correct. Specifically in my case, mergers at (or very close to) ZAMS are much more likely to be observationally identified as single, more massive stars, which we in principle account for with the IMF. So removing these binaries completely is more self-consistent.

**Comment by jeffriley** [comment]
Perhaps I explained what I meant poorly.  Here's what I meant:

1. If --allow-rlof-at-birth is true we allow stars that are undergoing RLOF at birth to enter the population of stars that make up our binaries.
2. If CHE is enabled, we assume the components are tidally locked, and set the rotational frequency of each component to the orbital frequency of the binary (or is it angular velocity? Just a factor...)
3. If a star is rotating above the metallicity-dependent CHE threshold, then we declare the star a CH star and evolve via CHE
4. For CH stars we recalculate the star's rotational frequency at each timestep, and if it has spun down below the CHE threshold, we switch it to an MS star and evolve it from there as an MS star (Edit: for CHE mode = PESSIMISTIC.  For OPTIMISTIC we assume born CH always CH)

So that already exists in COMPAS.  What I meant was that there will be a range of initial masses for the component stars, and that will mean some binaries will have stars that are rotating fast enough to evolve via CHE, and some will not - and the ones that don't might have really big stars that are close together that are just not rotating fast enough to be considered CH stars, so those binaries will not evolve via CHE and they will probably merge in the first few timesteps.  just the luck of the draw - if they were rotating a bit faster they'd survive as CH stars past the first few timesteps.

So, I think where our disconnect is here is in your statement:

> But here we're saying that binaries in RLOF at precisely ZAMS should survive, but immediately after that they should merge, which is not physical or correct.

My understanding of the --allow-rlof-at-birth option is not that we are allowing, or expecting, such binaries to survive, but merely that we are allowing the binary to take its chances evolving.  Prior to the implementation of the --allow-rlof-at-birth option we didn't allow such binaries to be part of our population because we expected them to merge almost immediately, so we might as well consider them as mergers at birth and so not actually binary stars.  With the advent of CHE and --allow-rlof-at-birth that changed.  The way I look at --allow-rlof-at-birth is that when that option is true, we consider that the binary is born as a binary even if one or both components are undergoing RLOF at birth, and we'll let it take its chances at evolution.  If we also have CHE enabled, some of the binaries might survive and produce DCOs, and some might not - but we let all of them try.  So we're not saying "immediately after that they should merge" - it's just that if CHE is enabled some will merge in the first few timesteps (if they're not spinning fast enough), and if CHE is not enabled they will probably all merge in the first few timesteps.

> ...which is not physical or correct

Why is that so?  I don't know the answer to this, so this is a serious, non-rhetorical, question.  Why must they merge precisely at birth for it to be considered physical and correct?  Is is not possible (i.e. physical and correct) for two stars to be born very close together, so close that one or both is in RLOF at birth, and take some finite time (a timestep or two) to actually merge?

So, if I evolve a single binary with the following command:

    ./compas --mode bse -n1 --initial-mass-1 6.067973 --initial-mass-2 2.956799 --semi-major-axis 0.0337185

I get a stellar merger at the 29th timestep.  It doesn't matter how many times I run COMPAS, or what random seed I use, I always get a stellar merger at timestep 29.  Why should we not check for that combination of initial masses and exclude that binary from the COMPAS population?  We know it's going to merge in very few timesteps.  In fact, if I execute this command:

    ./compas --mode bse -n1 --initial-mass-1 6.067973 --initial-mass-2 2.956799 --semi-major-axis 0.0337185 --timestep-multiplier 100

the binary merges in the 3rd timestep - not so different from a binary that might have been undergoing RLOF at birth and that didn't evolve via CHE.  So why shouldn't we exclude it (and any other combination that we can calculate will similarly merge)?

So I think, as I said, our disconnect is how we interpret the --allow-rlof-at-birth option.  RLOF isn't merger.  I interpret the option as "include all binaries (except those that are actually touching - they are governed by --allow-touching-at-birth) and let them evolve and see what happens".  I think you interpret it differently - I think you interpret it such that setting --allow-rlof-at-birth true ensures not only that the binary is allowed to evolve, that it should survive for some finite time longer than the first few timesteps?

My interpretation might be completely wrong - I just assumed that was what was meant when we implemented it.

**Comment by reinhold-willcox** [comment]
As noted in PR #785, the issue outlined here is not sufficiently problematic to warrant further attention, so I'm closing the issue. A future student who is implementing over-contact binary prescriptions may want to consider and/or reopen this issue.
