### ISSUE TITLE
SSE doesn't read grid file.

### ISSUE THREAD

**Issue by jmerritt1** [TeamCOMPAS/COMPAS#852]
**Describe the bug**
When running using runSubmit.py, compasConfigDefault.yaml with SSE, and a grid file, the run samples from the range of masses rather than using exact masses specified in the grid file. It does successfully use the provided metallicities. With BSE, the masses _are_ correctly pulled from the grid file.

**Label the issue**
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
1. run with compasConfigDefault.yaml, specifying SSE
2. use the grid file in `COMPAS/utils/examples/methods_paper_plots/fig_5_HR_diagram/grid.txt`

**Expected behavior**
Expected to use the masses specified in each line of the grid file.

**Versioning (please complete the following information):**
 - OS:  Ubuntu 20.04.5 LTS
 - COMPAS v02.33.00

**Comment by jeffriley** [comment]
This works on the commandline:

./compas --mode SSE --grid ssegrid.txt

where the file ssegrid.txt contains:

    --initial-mass 2.3
    --initial-mass 12.75
    --initial-mass 20.3
    --initial-mass 8
    --initial-mass 7.0

and produces the expected output.

The problem here is that the grid file specified 

    COMPAS/utils/examples/methods_paper_plots/fig_5_HR_diagram/grid.txt

contains

    --initial-mass-1 0.5 --initial-mass-2 0.1 --metallicity 0.0142 --eccentricity 0.0 --semi-major-axis 1e+20 
    --initial-mass-1 0.65 --initial-mass-2 0.1 --metallicity 0.0142 --eccentricity 0.0 --semi-major-axis 1e+20 
    --initial-mass-1 0.8 --initial-mass-2 0.1 --metallicity 0.0142 --eccentricity 0.0 --semi-major-axis 1e+20 
    ...

which is a BSE grid file - those options are BSE mode specific (SSE mode doesn't know what ``--initial-mass-1`` is, or ``--semi-major-axis`` ...

COMPAS will ignore BSE options in SSE mode (and vice versa), so I think you are seeing the expected result (without actually looking at what you are seeing...).

@jmerritt1 let me know if this doesn't resolve the issue.

**Comment by jmerritt1** [comment]
Okay, I'll keep learning the program options. I'll have this in mind when using SSE. Thanks!
