### ISSUE TITLE
Remind user of distinct flags for remnant mass prescription and kick magnitude prescription

### ISSUE THREAD

**Issue by IsobelMarguarethe** [TeamCOMPAS/COMPAS#913]
Setting the `--kick-manitude-prescription` to e.g. `MULLERMANDEL` does not automatically set the `--remnant-mass-prescription` to `MULLERMANDEL`.

While we want to retain flexibility, this may lead users unfamiliar with the full program options list to misunderstand the settings they've chosen.

A solution might be:
- Add a note in the documentation for both of these flags, pointing to the other one and advising users to make sure they have set both flags appropriately
- Print a warning if the options don't match (not an error, just make a mismatching selection transparent to the user)

An alternative would be to automatically set one flag based on the other if they are not set explicitly. This retains flexibility since a user-supplied setting would still take precedence.

**Comment by ilyamandel** [comment]
Added 

Note that this is independent from ``--remnant-mass-prescription`` to provide flexibility; 
however, if using ``MULLERMANDEL'', it is recommended to keep them consistent by doing so for both. |br|

in both places to the documentation (see PR #915 ).

Warnings are rather tricky here because many combinations are possible, and some are intended to work together -- so I don't see a clear argument for when warnings should be created.

Closing this issue.
